[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139267157",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139267157",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139267157,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTI2NzE1Nw==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-10T14:41:17Z",
    "updated_at": "2015-09-10T14:41:17Z",
    "author_association": "MEMBER",
    "body": "What do you get from `pip list`, and `python -m platform`?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139267231",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139267231",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139267231,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTI2NzIzMQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-10T14:41:33Z",
    "updated_at": "2015-09-10T14:41:33Z",
    "author_association": "MEMBER",
    "body": "And what is the exact path that's failing?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139284088",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139284088",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139284088,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTI4NDA4OA==",
    "user": {
      "login": "vext01",
      "id": 604955,
      "node_id": "MDQ6VXNlcjYwNDk1NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/604955?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vext01",
      "html_url": "https://github.com/vext01",
      "followers_url": "https://api.github.com/users/vext01/followers",
      "following_url": "https://api.github.com/users/vext01/following{/other_user}",
      "gists_url": "https://api.github.com/users/vext01/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vext01/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vext01/subscriptions",
      "organizations_url": "https://api.github.com/users/vext01/orgs",
      "repos_url": "https://api.github.com/users/vext01/repos",
      "events_url": "https://api.github.com/users/vext01/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vext01/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-10T15:37:23Z",
    "updated_at": "2015-09-10T15:37:23Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hey,\n\nThanks for getting back to me. I've just tried again using a fresh python-2.7 virtualenv. Sure enough, we still have the issue.\n\nThe failing path is: `http://localhost:8888/tree`\n\npip list:\n\n```\n$ /tmp/ve/bin/pip list\nYou are using pip version 7.0.3, however version 7.1.2 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\nbackports.ssl-match-hostname (3.4.0.2)\ncertifi (2015.9.6.2)\ndecorator (4.0.2)\nfunctools32 (3.2.3.post2)\nipykernel (4.0.3)\nipython (4.0.0)\nipython-genutils (0.1.0)\nJinja2 (2.8)\njsonschema (2.5.1)\njupyter-client (4.0.0)\njupyter-core (4.0.4)\nMarkupSafe (0.23)\nmistune (0.7.1)\nnbconvert (4.0.0)\nnbformat (4.0.0)\nnotebook (4.0.4)\npath.py (8.1.1)\npexpect (3.3)\npickleshare (0.5)\npip (7.0.3)\nptyprocess (0.5)\nPygments (2.0.2)\npyzmq (14.7.0)\nsetuptools (17.0)\nsimplegeneric (0.8.1)\nterminado (0.5)\ntornado (4.2.1)\ntraitlets (4.0.0)\nwheel (0.24.0)\n```\n\nplatform:\n\n```\nOpenBSD-5.8-amd64-64bit\n```\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139285521",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139285521",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139285521,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTI4NTUyMQ==",
    "user": {
      "login": "vext01",
      "id": 604955,
      "node_id": "MDQ6VXNlcjYwNDk1NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/604955?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vext01",
      "html_url": "https://github.com/vext01",
      "followers_url": "https://api.github.com/users/vext01/followers",
      "following_url": "https://api.github.com/users/vext01/following{/other_user}",
      "gists_url": "https://api.github.com/users/vext01/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vext01/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vext01/subscriptions",
      "organizations_url": "https://api.github.com/users/vext01/orgs",
      "repos_url": "https://api.github.com/users/vext01/repos",
      "events_url": "https://api.github.com/users/vext01/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vext01/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-10T15:41:20Z",
    "updated_at": "2015-09-10T15:41:20Z",
    "author_association": "CONTRIBUTOR",
    "body": "I've just tried using a python3.4 virtualenv. The traceback does not occur under this setup.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139362781",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139362781",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139362781,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTM2Mjc4MQ==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-10T19:54:32Z",
    "updated_at": "2015-09-10T19:54:32Z",
    "author_association": "MEMBER",
    "body": "@vext01 sorry, I meant the filesystem path that's failing. Can you send the path on the filesystem, and a listing of the directory that it's trying to list?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139379383",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139379383",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139379383,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTM3OTM4Mw==",
    "user": {
      "login": "vext01",
      "id": 604955,
      "node_id": "MDQ6VXNlcjYwNDk1NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/604955?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vext01",
      "html_url": "https://github.com/vext01",
      "followers_url": "https://api.github.com/users/vext01/followers",
      "following_url": "https://api.github.com/users/vext01/following{/other_user}",
      "gists_url": "https://api.github.com/users/vext01/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vext01/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vext01/subscriptions",
      "organizations_url": "https://api.github.com/users/vext01/orgs",
      "repos_url": "https://api.github.com/users/vext01/repos",
      "events_url": "https://api.github.com/users/vext01/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vext01/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-10T21:09:15Z",
    "updated_at": "2015-09-10T21:09:15Z",
    "author_association": "CONTRIBUTOR",
    "body": "Hey.\n\nI'm not at my computer, but it was just my home directory. So you suspect a\nfilename is causing the crash? I can try later with another path, and look\nfor troublesome characters in filenames in my home directory.\n\nCheers\nOn 10 Sep 2015 21:54, \"Min RK\" notifications@github.com wrote:\n\n> @vext01 https://github.com/vext01 sorry, I meant the filesystem path\n> that's failing. Can you send the path on the filesystem, and a listing of\n> the directory that it's trying to list?\n> \n> —\n> Reply to this email directly or view it on GitHub\n> https://github.com/jupyter/notebook/issues/287#issuecomment-139362781.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139481858",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139481858",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139481858,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTQ4MTg1OA==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-11T08:22:12Z",
    "updated_at": "2015-09-11T08:22:12Z",
    "author_association": "MEMBER",
    "body": "There is a non-ascii path somewhere, causing the failure. It is presumably in one of two places:\n1. the directory being listed, or\n2. one of the filenames in the listing\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139578194",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139578194",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139578194,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTU3ODE5NA==",
    "user": {
      "login": "vext01",
      "id": 604955,
      "node_id": "MDQ6VXNlcjYwNDk1NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/604955?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/vext01",
      "html_url": "https://github.com/vext01",
      "followers_url": "https://api.github.com/users/vext01/followers",
      "following_url": "https://api.github.com/users/vext01/following{/other_user}",
      "gists_url": "https://api.github.com/users/vext01/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/vext01/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/vext01/subscriptions",
      "organizations_url": "https://api.github.com/users/vext01/orgs",
      "repos_url": "https://api.github.com/users/vext01/repos",
      "events_url": "https://api.github.com/users/vext01/events{/privacy}",
      "received_events_url": "https://api.github.com/users/vext01/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-11T15:36:15Z",
    "updated_at": "2015-09-11T15:36:15Z",
    "author_association": "CONTRIBUTOR",
    "body": "Ah, well here is the problem file:\n\n```\n-rw-------    1 edd   edd      1024 May 25  2014 .?    set document.colors.dirs = \"black\"??    ## document.colors.increase_contrast [\n```\n\nI would have been confused, but I know what this is all about. There was a bug in the elinks web browser (which IIRC is now fixed), which caused elinks to write a file whose name was (some of) the contents of the elinks config file. This is one such file.\n\nObviously filename is crazy, but we could try to make this a little more robust. Something like this:\n\n```\n--- filemanager.py.orig Fri Sep 11 16:29:30 2015\n+++ filemanager.py  Fri Sep 11 16:32:56 2015\n@@ -246,7 +246,12 @@\n             model['content'] = contents = []\n             os_dir = self._get_os_path(path)\n             for name in os.listdir(os_dir):\n-                os_path = os.path.join(os_dir, name)\n+                try:\n+                    os_path = os.path.join(os_dir, name)\n+                except UnicodeDecodeError as e:\n+                    self.log.warn(\n+                        \"failed to decode filename '%s': %s\", name, e)\n+                    continue\n                 # skip over broken symlinks in listing\n                 if not os.path.exists(os_path):\n                     self.log.warn(\"%s doesn't exist\", os_path)\n```\n\nCheers\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/139587888",
    "html_url": "https://github.com/jupyter/notebook/issues/287#issuecomment-139587888",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/287",
    "id": 139587888,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEzOTU4Nzg4OA==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-11T16:11:47Z",
    "updated_at": "2015-09-11T16:11:47Z",
    "author_association": "MEMBER",
    "body": "do you want to try sending a PR ?\n",
    "performed_via_github_app": null
  }
]
