[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/196345533",
    "html_url": "https://github.com/jupyter/notebook/issues/1205#issuecomment-196345533",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1205",
    "id": 196345533,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE5NjM0NTUzMw==",
    "user": {
      "login": "acasimiro",
      "id": 44839,
      "node_id": "MDQ6VXNlcjQ0ODM5",
      "avatar_url": "https://avatars.githubusercontent.com/u/44839?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/acasimiro",
      "html_url": "https://github.com/acasimiro",
      "followers_url": "https://api.github.com/users/acasimiro/followers",
      "following_url": "https://api.github.com/users/acasimiro/following{/other_user}",
      "gists_url": "https://api.github.com/users/acasimiro/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/acasimiro/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/acasimiro/subscriptions",
      "organizations_url": "https://api.github.com/users/acasimiro/orgs",
      "repos_url": "https://api.github.com/users/acasimiro/repos",
      "events_url": "https://api.github.com/users/acasimiro/events{/privacy}",
      "received_events_url": "https://api.github.com/users/acasimiro/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-03-14T14:47:11Z",
    "updated_at": "2016-03-14T14:47:11Z",
    "author_association": "NONE",
    "body": "This issue is absolutely not related to jupyter notebook, sorry.\nThe problem occurred because in the meanwhile I changed my java version from 1.7 to 1.8.\nSolution: change back to java 7.\n",
    "performed_via_github_app": null
  }
]
