[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/416828466",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-416828466",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 416828466,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQxNjgyODQ2Ng==",
    "user": {
      "login": "gopinathvse",
      "id": 26655360,
      "node_id": "MDQ6VXNlcjI2NjU1MzYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/26655360?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/gopinathvse",
      "html_url": "https://github.com/gopinathvse",
      "followers_url": "https://api.github.com/users/gopinathvse/followers",
      "following_url": "https://api.github.com/users/gopinathvse/following{/other_user}",
      "gists_url": "https://api.github.com/users/gopinathvse/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/gopinathvse/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/gopinathvse/subscriptions",
      "organizations_url": "https://api.github.com/users/gopinathvse/orgs",
      "repos_url": "https://api.github.com/users/gopinathvse/repos",
      "events_url": "https://api.github.com/users/gopinathvse/events{/privacy}",
      "received_events_url": "https://api.github.com/users/gopinathvse/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-08-29T05:25:46Z",
    "updated_at": "2018-08-29T05:31:09Z",
    "author_association": "NONE",
    "body": "Uninstall the previous version and download the new version from below link\r\nhttps://www.python.org/downloads/\r\n\r\nAfter install run the command in terminal as follows:\r\npython -m pip install --upgrade pip\r\npython -m pip install jupyter\r\njupyter notebook\r\n\r\nIf you get any token problem or if it may ask any password run the command :\r\njupyter notebook password\r\n\r\nEnter new password , it shown like \"Wroted hashed password to designation folder\"\r\nNow again Run the command:\r\n jupyter notebook\r\nNow enter your  password:\r\nJupyter notebook gets launched successfully.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/433347128",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-433347128",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 433347128,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQzMzM0NzEyOA==",
    "user": {
      "login": "tsando",
      "id": 13929456,
      "node_id": "MDQ6VXNlcjEzOTI5NDU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/13929456?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tsando",
      "html_url": "https://github.com/tsando",
      "followers_url": "https://api.github.com/users/tsando/followers",
      "following_url": "https://api.github.com/users/tsando/following{/other_user}",
      "gists_url": "https://api.github.com/users/tsando/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tsando/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tsando/subscriptions",
      "organizations_url": "https://api.github.com/users/tsando/orgs",
      "repos_url": "https://api.github.com/users/tsando/repos",
      "events_url": "https://api.github.com/users/tsando/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tsando/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-10-26T09:28:50Z",
    "updated_at": "2018-10-26T09:28:50Z",
    "author_association": "NONE",
    "body": "I am getting a similar error but only on port 8889 - see my issue posted here https://github.com/jupyter/notebook/issues/4143 did reinstalling it as per the above suggestion solve your issue?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/439280600",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-439280600",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 439280600,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQzOTI4MDYwMA==",
    "user": {
      "login": "joelkim",
      "id": 523603,
      "node_id": "MDQ6VXNlcjUyMzYwMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/523603?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/joelkim",
      "html_url": "https://github.com/joelkim",
      "followers_url": "https://api.github.com/users/joelkim/followers",
      "following_url": "https://api.github.com/users/joelkim/following{/other_user}",
      "gists_url": "https://api.github.com/users/joelkim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/joelkim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/joelkim/subscriptions",
      "organizations_url": "https://api.github.com/users/joelkim/orgs",
      "repos_url": "https://api.github.com/users/joelkim/repos",
      "events_url": "https://api.github.com/users/joelkim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/joelkim/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-16T04:44:30Z",
    "updated_at": "2018-11-16T04:44:30Z",
    "author_association": "NONE",
    "body": "I have the same error on port 8888\r\n\r\n<img width=\"736\" alt=\"2018-11-16 1 44 01\" src=\"https://user-images.githubusercontent.com/523603/48598332-b5933800-e9a5-11e8-9406-a7c6542f22d4.png\">\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/439341790",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-439341790",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 439341790,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQzOTM0MTc5MA==",
    "user": {
      "login": "tsando",
      "id": 13929456,
      "node_id": "MDQ6VXNlcjEzOTI5NDU2",
      "avatar_url": "https://avatars.githubusercontent.com/u/13929456?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tsando",
      "html_url": "https://github.com/tsando",
      "followers_url": "https://api.github.com/users/tsando/followers",
      "following_url": "https://api.github.com/users/tsando/following{/other_user}",
      "gists_url": "https://api.github.com/users/tsando/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tsando/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tsando/subscriptions",
      "organizations_url": "https://api.github.com/users/tsando/orgs",
      "repos_url": "https://api.github.com/users/tsando/repos",
      "events_url": "https://api.github.com/users/tsando/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tsando/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-16T09:56:17Z",
    "updated_at": "2018-11-16T09:56:17Z",
    "author_association": "NONE",
    "body": "Does anyone have any solutions for this error? I still haven't been able to get rid of it... Thanks.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/439345901",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-439345901",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 439345901,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQzOTM0NTkwMQ==",
    "user": {
      "login": "joelkim",
      "id": 523603,
      "node_id": "MDQ6VXNlcjUyMzYwMw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/523603?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/joelkim",
      "html_url": "https://github.com/joelkim",
      "followers_url": "https://api.github.com/users/joelkim/followers",
      "following_url": "https://api.github.com/users/joelkim/following{/other_user}",
      "gists_url": "https://api.github.com/users/joelkim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/joelkim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/joelkim/subscriptions",
      "organizations_url": "https://api.github.com/users/joelkim/orgs",
      "repos_url": "https://api.github.com/users/joelkim/repos",
      "events_url": "https://api.github.com/users/joelkim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/joelkim/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-16T10:10:52Z",
    "updated_at": "2018-11-16T10:10:52Z",
    "author_association": "NONE",
    "body": "I cleared all caches and cookies, and it is solved.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/440490097",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-440490097",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 440490097,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MDQ5MDA5Nw==",
    "user": {
      "login": "rattanakchea",
      "id": 3496405,
      "node_id": "MDQ6VXNlcjM0OTY0MDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3496405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rattanakchea",
      "html_url": "https://github.com/rattanakchea",
      "followers_url": "https://api.github.com/users/rattanakchea/followers",
      "following_url": "https://api.github.com/users/rattanakchea/following{/other_user}",
      "gists_url": "https://api.github.com/users/rattanakchea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rattanakchea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rattanakchea/subscriptions",
      "organizations_url": "https://api.github.com/users/rattanakchea/orgs",
      "repos_url": "https://api.github.com/users/rattanakchea/repos",
      "events_url": "https://api.github.com/users/rattanakchea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rattanakchea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-21T01:06:33Z",
    "updated_at": "2018-11-21T01:06:33Z",
    "author_association": "NONE",
    "body": "For me, this is caused by a chrome extension named CORS. After I uninstalled the extension, it works.\r\nI would try to uninstall any recently installed extensions.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/440490237",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-440490237",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 440490237,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0MDQ5MDIzNw==",
    "user": {
      "login": "rattanakchea",
      "id": 3496405,
      "node_id": "MDQ6VXNlcjM0OTY0MDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3496405?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rattanakchea",
      "html_url": "https://github.com/rattanakchea",
      "followers_url": "https://api.github.com/users/rattanakchea/followers",
      "following_url": "https://api.github.com/users/rattanakchea/following{/other_user}",
      "gists_url": "https://api.github.com/users/rattanakchea/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rattanakchea/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rattanakchea/subscriptions",
      "organizations_url": "https://api.github.com/users/rattanakchea/orgs",
      "repos_url": "https://api.github.com/users/rattanakchea/repos",
      "events_url": "https://api.github.com/users/rattanakchea/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rattanakchea/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-11-21T01:07:15Z",
    "updated_at": "2018-11-21T01:07:15Z",
    "author_association": "NONE",
    "body": "> Hello to all,\r\n> \r\n> I opened my Jupyter Notebook today and created a new Pyhton 3 Notebook, I have not intentionally changed anything since the last time I used it, but today I'm getting a blank page and when I look in the chrome console I get these errors.\r\n> \r\n> index.js:1 Uncaught SyntaxError: Invalid or unexpected token\r\n> index.js:1 Uncaught SyntaxError: Invalid or unexpected token\r\n> index.js:1 Uncaught SyntaxError: Invalid or unexpected token\r\n> require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 ReferenceError: preact is not defined\r\n> at shortcuteditor.js:15\r\n> at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)\r\n> at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)\r\n> at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177)\r\n> at Object.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1550)\r\n> at Module. (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1162)\r\n> at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131\r\n> at each (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56)\r\n> at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1114)\r\n> at Object.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1550)\r\n> check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900\r\n> require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 TypeError: Cannot read property 'ShortcutEditor' of undefined\r\n> at notebook.js:66\r\n> at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)\r\n> at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)\r\n> at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177)\r\n> at Object.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1550)\r\n> at Module. (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1162)\r\n> at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131\r\n> at each (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56)\r\n> at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1114)\r\n> at Module.init (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:783)\r\n> check @ require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900\r\n> require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 TypeError: Cannot read property 'Notebook' of undefined\r\n> at main.js:127\r\n> at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)\r\n> at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)\r\n> at Module. (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140)\r\n> at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131\r\n> at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190\r\n> at each (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:56)\r\n> at Module.emit (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1189)\r\n> at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:940)\r\n> at Module.enable (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1177)\r\n> \r\n> Could anyone help find how to fix this issue. There are no errors in the terminal and I have also looked at the post\r\n> \r\n> _When opening a notebook file, the browser displays a blank screen #1627_\r\n> \r\n> and this did not propose any solutions.\r\n> \r\n> Thank you\r\n\r\nFor me, this is caused by a chrome extension named CORS. After I uninstalled the extension, it works.\r\nI would try to uninstall any recently installed extensions.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/474233278",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-474233278",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 474233278,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NDIzMzI3OA==",
    "user": {
      "login": "ZhiyuanChen",
      "id": 28757366,
      "node_id": "MDQ6VXNlcjI4NzU3MzY2",
      "avatar_url": "https://avatars.githubusercontent.com/u/28757366?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ZhiyuanChen",
      "html_url": "https://github.com/ZhiyuanChen",
      "followers_url": "https://api.github.com/users/ZhiyuanChen/followers",
      "following_url": "https://api.github.com/users/ZhiyuanChen/following{/other_user}",
      "gists_url": "https://api.github.com/users/ZhiyuanChen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ZhiyuanChen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ZhiyuanChen/subscriptions",
      "organizations_url": "https://api.github.com/users/ZhiyuanChen/orgs",
      "repos_url": "https://api.github.com/users/ZhiyuanChen/repos",
      "events_url": "https://api.github.com/users/ZhiyuanChen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ZhiyuanChen/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-19T07:50:21Z",
    "updated_at": "2019-03-19T07:50:21Z",
    "author_association": "NONE",
    "body": "I tried on Edge and IE which display nothing either",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/474653207",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-474653207",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 474653207,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NDY1MzIwNw==",
    "user": {
      "login": "etoricky",
      "id": 11624396,
      "node_id": "MDQ6VXNlcjExNjI0Mzk2",
      "avatar_url": "https://avatars.githubusercontent.com/u/11624396?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/etoricky",
      "html_url": "https://github.com/etoricky",
      "followers_url": "https://api.github.com/users/etoricky/followers",
      "following_url": "https://api.github.com/users/etoricky/following{/other_user}",
      "gists_url": "https://api.github.com/users/etoricky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/etoricky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/etoricky/subscriptions",
      "organizations_url": "https://api.github.com/users/etoricky/orgs",
      "repos_url": "https://api.github.com/users/etoricky/repos",
      "events_url": "https://api.github.com/users/etoricky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/etoricky/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-20T01:56:38Z",
    "updated_at": "2019-03-20T01:57:32Z",
    "author_association": "NONE",
    "body": "I had the same \"Jupyter Notebook blank page\" problem.\r\n\r\nI used to use Anaconda and Jupyter Notebook worked fine. Recently I changed to \"Miniconda3-latest-Windows-x86_64\" and \"pip install jupyter\". after cmd.exe \"jupyter notebook\", both Chrome and Firefox shows a blank page where I can see some valid HTML code behind.\r\n\r\nMy solution? Use Anaconda instead of Minconda.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/475526223",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-475526223",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 475526223,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NTUyNjIyMw==",
    "user": {
      "login": "NMNSGR",
      "id": 14973010,
      "node_id": "MDQ6VXNlcjE0OTczMDEw",
      "avatar_url": "https://avatars.githubusercontent.com/u/14973010?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/NMNSGR",
      "html_url": "https://github.com/NMNSGR",
      "followers_url": "https://api.github.com/users/NMNSGR/followers",
      "following_url": "https://api.github.com/users/NMNSGR/following{/other_user}",
      "gists_url": "https://api.github.com/users/NMNSGR/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/NMNSGR/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/NMNSGR/subscriptions",
      "organizations_url": "https://api.github.com/users/NMNSGR/orgs",
      "repos_url": "https://api.github.com/users/NMNSGR/repos",
      "events_url": "https://api.github.com/users/NMNSGR/events{/privacy}",
      "received_events_url": "https://api.github.com/users/NMNSGR/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-22T07:57:52Z",
    "updated_at": "2019-03-22T07:57:52Z",
    "author_association": "NONE",
    "body": "The solution\r\n\r\n> I had the same \"Jupyter Notebook blank page\" problem.\r\n> \r\n> I used to use Anaconda and Jupyter Notebook worked fine. Recently I changed to \"Miniconda3-latest-Windows-x86_64\" and \"pip install jupyter\". after cmd.exe \"jupyter notebook\", both Chrome and Firefox shows a blank page where I can see some valid HTML code behind.\r\n> \r\n> My solution? Use Anaconda instead of Minconda.\r\n\r\nThe solution isnt Anaconda or Miniconda....This is happening with the latest Jupyter package installation irrespective of how you make the installation. There has to be a patch released by Jupyter to resolve this.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/475526450",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-475526450",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 475526450,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NTUyNjQ1MA==",
    "user": {
      "login": "NMNSGR",
      "id": 14973010,
      "node_id": "MDQ6VXNlcjE0OTczMDEw",
      "avatar_url": "https://avatars.githubusercontent.com/u/14973010?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/NMNSGR",
      "html_url": "https://github.com/NMNSGR",
      "followers_url": "https://api.github.com/users/NMNSGR/followers",
      "following_url": "https://api.github.com/users/NMNSGR/following{/other_user}",
      "gists_url": "https://api.github.com/users/NMNSGR/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/NMNSGR/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/NMNSGR/subscriptions",
      "organizations_url": "https://api.github.com/users/NMNSGR/orgs",
      "repos_url": "https://api.github.com/users/NMNSGR/repos",
      "events_url": "https://api.github.com/users/NMNSGR/events{/privacy}",
      "received_events_url": "https://api.github.com/users/NMNSGR/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-22T07:58:56Z",
    "updated_at": "2019-03-22T07:58:56Z",
    "author_association": "NONE",
    "body": "Right now it is best to not update the current Jupyter installations.\r\nI even tried installing older version on Jupyter and Notebook but to no avail.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/475947318",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-475947318",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 475947318,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NTk0NzMxOA==",
    "user": {
      "login": "Vincent-wq",
      "id": 11001776,
      "node_id": "MDQ6VXNlcjExMDAxNzc2",
      "avatar_url": "https://avatars.githubusercontent.com/u/11001776?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Vincent-wq",
      "html_url": "https://github.com/Vincent-wq",
      "followers_url": "https://api.github.com/users/Vincent-wq/followers",
      "following_url": "https://api.github.com/users/Vincent-wq/following{/other_user}",
      "gists_url": "https://api.github.com/users/Vincent-wq/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Vincent-wq/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Vincent-wq/subscriptions",
      "organizations_url": "https://api.github.com/users/Vincent-wq/orgs",
      "repos_url": "https://api.github.com/users/Vincent-wq/repos",
      "events_url": "https://api.github.com/users/Vincent-wq/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Vincent-wq/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-24T10:47:00Z",
    "updated_at": "2019-03-24T10:47:00Z",
    "author_association": "NONE",
    "body": "Hi, I think I am having the same problem, and it seems they jupyter notebook is never working well for me (last time, it is extremely slow), the situation now is:\r\nwin10, 64bit, anaconda (most recent version), new env named mne, the jupyter notebook for base environment is working but the one for mne is not working, showing blank page, and update jupyter does not help, here is the screen shot, thanks for your attentions.\r\n![jupyternote](https://user-images.githubusercontent.com/11001776/54878264-333fe680-4e65-11e9-9c1a-e6f8c9174fa2.png)\r\n\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/476488010",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-476488010",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 476488010,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NjQ4ODAxMA==",
    "user": {
      "login": "adimukewar",
      "id": 25963841,
      "node_id": "MDQ6VXNlcjI1OTYzODQx",
      "avatar_url": "https://avatars.githubusercontent.com/u/25963841?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/adimukewar",
      "html_url": "https://github.com/adimukewar",
      "followers_url": "https://api.github.com/users/adimukewar/followers",
      "following_url": "https://api.github.com/users/adimukewar/following{/other_user}",
      "gists_url": "https://api.github.com/users/adimukewar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/adimukewar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/adimukewar/subscriptions",
      "organizations_url": "https://api.github.com/users/adimukewar/orgs",
      "repos_url": "https://api.github.com/users/adimukewar/repos",
      "events_url": "https://api.github.com/users/adimukewar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/adimukewar/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-26T06:06:07Z",
    "updated_at": "2019-03-26T06:06:07Z",
    "author_association": "NONE",
    "body": "I am facing a similar problem, I tried all the solutions mentioned in the discussion. I even tried reinstalling Anaconda Prompt.\r\nHas anybody faced a similar issue?\r\n\r\n![jupyter](https://user-images.githubusercontent.com/25963841/54974730-441a5600-4f52-11e9-8776-089c77f23b90.png)\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/476578079",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-476578079",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 476578079,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NjU3ODA3OQ==",
    "user": {
      "login": "NMNSGR",
      "id": 14973010,
      "node_id": "MDQ6VXNlcjE0OTczMDEw",
      "avatar_url": "https://avatars.githubusercontent.com/u/14973010?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/NMNSGR",
      "html_url": "https://github.com/NMNSGR",
      "followers_url": "https://api.github.com/users/NMNSGR/followers",
      "following_url": "https://api.github.com/users/NMNSGR/following{/other_user}",
      "gists_url": "https://api.github.com/users/NMNSGR/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/NMNSGR/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/NMNSGR/subscriptions",
      "organizations_url": "https://api.github.com/users/NMNSGR/orgs",
      "repos_url": "https://api.github.com/users/NMNSGR/repos",
      "events_url": "https://api.github.com/users/NMNSGR/events{/privacy}",
      "received_events_url": "https://api.github.com/users/NMNSGR/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-26T11:05:09Z",
    "updated_at": "2019-03-26T11:05:09Z",
    "author_association": "NONE",
    "body": "Solved it after a lot of pain......\r\nI am not using Conda rather directly using python, so make adjustments accordingly for your conda setup.\r\nThe way to go is that you need to downgrade notebook, go to version 5.7.4\r\nThen in the browser launch jupyter and press SHIFT+F5 (refresh with reset cache)\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/476741387",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-476741387",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 476741387,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3Njc0MTM4Nw==",
    "user": {
      "login": "iPotaje",
      "id": 2437201,
      "node_id": "MDQ6VXNlcjI0MzcyMDE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2437201?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iPotaje",
      "html_url": "https://github.com/iPotaje",
      "followers_url": "https://api.github.com/users/iPotaje/followers",
      "following_url": "https://api.github.com/users/iPotaje/following{/other_user}",
      "gists_url": "https://api.github.com/users/iPotaje/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/iPotaje/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iPotaje/subscriptions",
      "organizations_url": "https://api.github.com/users/iPotaje/orgs",
      "repos_url": "https://api.github.com/users/iPotaje/repos",
      "events_url": "https://api.github.com/users/iPotaje/events{/privacy}",
      "received_events_url": "https://api.github.com/users/iPotaje/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-26T16:48:05Z",
    "updated_at": "2019-03-26T16:48:47Z",
    "author_association": "NONE",
    "body": "It seems it's a problem with version 5.7.6 of notebook, solved with 5.7.4\r\nconda install notebook=5.7.4",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/476806800",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-476806800",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 476806800,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NjgwNjgwMA==",
    "user": {
      "login": "n00bmind",
      "id": 7993989,
      "node_id": "MDQ6VXNlcjc5OTM5ODk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7993989?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/n00bmind",
      "html_url": "https://github.com/n00bmind",
      "followers_url": "https://api.github.com/users/n00bmind/followers",
      "following_url": "https://api.github.com/users/n00bmind/following{/other_user}",
      "gists_url": "https://api.github.com/users/n00bmind/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/n00bmind/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/n00bmind/subscriptions",
      "organizations_url": "https://api.github.com/users/n00bmind/orgs",
      "repos_url": "https://api.github.com/users/n00bmind/repos",
      "events_url": "https://api.github.com/users/n00bmind/events{/privacy}",
      "received_events_url": "https://api.github.com/users/n00bmind/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-26T19:16:14Z",
    "updated_at": "2019-03-26T19:16:14Z",
    "author_association": "NONE",
    "body": "Just confirming I had the exact same problem and downgrading with\r\n`pip --upgrade notebook==5.7.4`\r\nsolved it immediately for me.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/476826951",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-476826951",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 476826951,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NjgyNjk1MQ==",
    "user": {
      "login": "adimukewar",
      "id": 25963841,
      "node_id": "MDQ6VXNlcjI1OTYzODQx",
      "avatar_url": "https://avatars.githubusercontent.com/u/25963841?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/adimukewar",
      "html_url": "https://github.com/adimukewar",
      "followers_url": "https://api.github.com/users/adimukewar/followers",
      "following_url": "https://api.github.com/users/adimukewar/following{/other_user}",
      "gists_url": "https://api.github.com/users/adimukewar/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/adimukewar/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/adimukewar/subscriptions",
      "organizations_url": "https://api.github.com/users/adimukewar/orgs",
      "repos_url": "https://api.github.com/users/adimukewar/repos",
      "events_url": "https://api.github.com/users/adimukewar/events{/privacy}",
      "received_events_url": "https://api.github.com/users/adimukewar/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-26T20:07:18Z",
    "updated_at": "2019-03-26T20:07:18Z",
    "author_association": "NONE",
    "body": "Thanks a lot, @NMNSGR 's solution worked for me.\r\nI had tried clearing browsing history and cache through browser menu but SHIFT + F5 worked instantly after downgrading the jupyter. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/477073034",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-477073034",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 477073034,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NzA3MzAzNA==",
    "user": {
      "login": "JenicChen",
      "id": 16453227,
      "node_id": "MDQ6VXNlcjE2NDUzMjI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/16453227?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/JenicChen",
      "html_url": "https://github.com/JenicChen",
      "followers_url": "https://api.github.com/users/JenicChen/followers",
      "following_url": "https://api.github.com/users/JenicChen/following{/other_user}",
      "gists_url": "https://api.github.com/users/JenicChen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/JenicChen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/JenicChen/subscriptions",
      "organizations_url": "https://api.github.com/users/JenicChen/orgs",
      "repos_url": "https://api.github.com/users/JenicChen/repos",
      "events_url": "https://api.github.com/users/JenicChen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/JenicChen/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-27T10:01:41Z",
    "updated_at": "2019-03-27T10:02:50Z",
    "author_association": "NONE",
    "body": "I had met the same problem and solved it by downgrading with version 5.7.4\r\nand  shift+F5 does really work!",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/477149574",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-477149574",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 477149574,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NzE0OTU3NA==",
    "user": {
      "login": "andreus42",
      "id": 33599923,
      "node_id": "MDQ6VXNlcjMzNTk5OTIz",
      "avatar_url": "https://avatars.githubusercontent.com/u/33599923?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/andreus42",
      "html_url": "https://github.com/andreus42",
      "followers_url": "https://api.github.com/users/andreus42/followers",
      "following_url": "https://api.github.com/users/andreus42/following{/other_user}",
      "gists_url": "https://api.github.com/users/andreus42/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/andreus42/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/andreus42/subscriptions",
      "organizations_url": "https://api.github.com/users/andreus42/orgs",
      "repos_url": "https://api.github.com/users/andreus42/repos",
      "events_url": "https://api.github.com/users/andreus42/events{/privacy}",
      "received_events_url": "https://api.github.com/users/andreus42/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-27T13:18:50Z",
    "updated_at": "2019-03-27T13:18:50Z",
    "author_association": "NONE",
    "body": "Yes!\r\npip install jupyter==5.7.4\r\nWorked for me and a shift+F5 was required.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/477204773",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-477204773",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 477204773,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NzIwNDc3Mw==",
    "user": {
      "login": "Tisagh",
      "id": 39168335,
      "node_id": "MDQ6VXNlcjM5MTY4MzM1",
      "avatar_url": "https://avatars.githubusercontent.com/u/39168335?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Tisagh",
      "html_url": "https://github.com/Tisagh",
      "followers_url": "https://api.github.com/users/Tisagh/followers",
      "following_url": "https://api.github.com/users/Tisagh/following{/other_user}",
      "gists_url": "https://api.github.com/users/Tisagh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Tisagh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Tisagh/subscriptions",
      "organizations_url": "https://api.github.com/users/Tisagh/orgs",
      "repos_url": "https://api.github.com/users/Tisagh/repos",
      "events_url": "https://api.github.com/users/Tisagh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Tisagh/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-27T15:18:34Z",
    "updated_at": "2019-03-27T15:18:34Z",
    "author_association": "NONE",
    "body": "> \r\n> \r\n> Yes!\r\n> pip install jupyter==5.7.4\r\n> Worked for me and a shift+F5 was required.\r\n\r\nSame here\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/477317280",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-477317280",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 477317280,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ3NzMxNzI4MA==",
    "user": {
      "login": "ubaidseth",
      "id": 5719905,
      "node_id": "MDQ6VXNlcjU3MTk5MDU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5719905?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ubaidseth",
      "html_url": "https://github.com/ubaidseth",
      "followers_url": "https://api.github.com/users/ubaidseth/followers",
      "following_url": "https://api.github.com/users/ubaidseth/following{/other_user}",
      "gists_url": "https://api.github.com/users/ubaidseth/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ubaidseth/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ubaidseth/subscriptions",
      "organizations_url": "https://api.github.com/users/ubaidseth/orgs",
      "repos_url": "https://api.github.com/users/ubaidseth/repos",
      "events_url": "https://api.github.com/users/ubaidseth/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ubaidseth/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-03-27T19:36:42Z",
    "updated_at": "2019-03-27T19:36:42Z",
    "author_association": "NONE",
    "body": "It works but wouldn't connect to kernel.\r\n\r\nI also had to downgrade tornado \r\nwith pip - **sudo python3.6 -m pip install tornado==4.5.3**\r\nwith conda - **conda install tornado==4.5.3**\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/495459094",
    "html_url": "https://github.com/jupyter/notebook/issues/3857#issuecomment-495459094",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3857",
    "id": 495459094,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NTQ1OTA5NA==",
    "user": {
      "login": "Cosin777",
      "id": 26279687,
      "node_id": "MDQ6VXNlcjI2Mjc5Njg3",
      "avatar_url": "https://avatars.githubusercontent.com/u/26279687?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Cosin777",
      "html_url": "https://github.com/Cosin777",
      "followers_url": "https://api.github.com/users/Cosin777/followers",
      "following_url": "https://api.github.com/users/Cosin777/following{/other_user}",
      "gists_url": "https://api.github.com/users/Cosin777/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Cosin777/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Cosin777/subscriptions",
      "organizations_url": "https://api.github.com/users/Cosin777/orgs",
      "repos_url": "https://api.github.com/users/Cosin777/repos",
      "events_url": "https://api.github.com/users/Cosin777/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Cosin777/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-05-24T03:25:54Z",
    "updated_at": "2019-05-24T03:25:54Z",
    "author_association": "NONE",
    "body": "> I cleared all caches and cookies, and it is solved.\r\n\r\n\r\n\r\n> I cleared all caches and cookies, and it is solved.\r\n\r\nSolved by cleaning all caches and cookies!\r\n\r\nI have blank page problem for a particular env， the others with old version jupyter don't have the problem.\r\nI tried Chrome, and Edge, none is working.",
    "performed_via_github_app": null
  }
]
