[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/286426058",
    "html_url": "https://github.com/jupyter/notebook/issues/2285#issuecomment-286426058",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2285",
    "id": 286426058,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI4NjQyNjA1OA==",
    "user": {
      "login": "EgZvor",
      "id": 11237935,
      "node_id": "MDQ6VXNlcjExMjM3OTM1",
      "avatar_url": "https://avatars.githubusercontent.com/u/11237935?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/EgZvor",
      "html_url": "https://github.com/EgZvor",
      "followers_url": "https://api.github.com/users/EgZvor/followers",
      "following_url": "https://api.github.com/users/EgZvor/following{/other_user}",
      "gists_url": "https://api.github.com/users/EgZvor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/EgZvor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/EgZvor/subscriptions",
      "organizations_url": "https://api.github.com/users/EgZvor/orgs",
      "repos_url": "https://api.github.com/users/EgZvor/repos",
      "events_url": "https://api.github.com/users/EgZvor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/EgZvor/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-14T13:48:44Z",
    "updated_at": "2017-03-14T13:48:44Z",
    "author_association": "NONE",
    "body": "To be honest I'm not sure how this affects configs, since I don't use any. Everything seems to work though.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/286460460",
    "html_url": "https://github.com/jupyter/notebook/issues/2285#issuecomment-286460460",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2285",
    "id": 286460460,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI4NjQ2MDQ2MA==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-03-14T15:37:02Z",
    "updated_at": "2017-03-14T15:37:02Z",
    "author_association": "MEMBER",
    "body": "It should be passing the path around as a unicode object, but it seems to be ending up as bytes somewhere. I'm not sure how to debug that.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/311990496",
    "html_url": "https://github.com/jupyter/notebook/issues/2285#issuecomment-311990496",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2285",
    "id": 311990496,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMxMTk5MDQ5Ng==",
    "user": {
      "login": "CrocodileDandy",
      "id": 5272909,
      "node_id": "MDQ6VXNlcjUyNzI5MDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5272909?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CrocodileDandy",
      "html_url": "https://github.com/CrocodileDandy",
      "followers_url": "https://api.github.com/users/CrocodileDandy/followers",
      "following_url": "https://api.github.com/users/CrocodileDandy/following{/other_user}",
      "gists_url": "https://api.github.com/users/CrocodileDandy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CrocodileDandy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CrocodileDandy/subscriptions",
      "organizations_url": "https://api.github.com/users/CrocodileDandy/orgs",
      "repos_url": "https://api.github.com/users/CrocodileDandy/repos",
      "events_url": "https://api.github.com/users/CrocodileDandy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CrocodileDandy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-06-29T14:49:46Z",
    "updated_at": "2017-06-29T14:49:46Z",
    "author_association": "NONE",
    "body": "Hi,\r\nI get the exact same here simply with IPython 5.1.0 and Python 3.6.0 embedded in Anaconda. I have a simple non-ascii 'Ã©' in my username.\r\nI simply run IPython with PowerShell and I get the same error. Plus, it forbids IPython to configure correctly. The autoreload I set up is then nonexistent. Indeed the path is bytes rather than unicode.\r\nMuch <3",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/312667623",
    "html_url": "https://github.com/jupyter/notebook/issues/2285#issuecomment-312667623",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2285",
    "id": 312667623,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMxMjY2NzYyMw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-07-03T14:58:20Z",
    "updated_at": "2017-07-03T14:58:20Z",
    "author_association": "MEMBER",
    "body": "I am unable to reproduce this with IPython 6.1 and Python 3.6. Can you try upgrading to the latest IPython?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/320951499",
    "html_url": "https://github.com/jupyter/notebook/issues/2285#issuecomment-320951499",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2285",
    "id": 320951499,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMDk1MTQ5OQ==",
    "user": {
      "login": "CrocodileDandy",
      "id": 5272909,
      "node_id": "MDQ6VXNlcjUyNzI5MDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5272909?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/CrocodileDandy",
      "html_url": "https://github.com/CrocodileDandy",
      "followers_url": "https://api.github.com/users/CrocodileDandy/followers",
      "following_url": "https://api.github.com/users/CrocodileDandy/following{/other_user}",
      "gists_url": "https://api.github.com/users/CrocodileDandy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/CrocodileDandy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/CrocodileDandy/subscriptions",
      "organizations_url": "https://api.github.com/users/CrocodileDandy/orgs",
      "repos_url": "https://api.github.com/users/CrocodileDandy/repos",
      "events_url": "https://api.github.com/users/CrocodileDandy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/CrocodileDandy/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-08-08T13:12:00Z",
    "updated_at": "2017-08-08T13:12:00Z",
    "author_association": "NONE",
    "body": "Just checked with IPython 6.1 and Python 3.6 on Windows 10.\r\n\r\nIpython fails to find its ipython_config.py file because the path gets fucked up because of my username.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/320961079",
    "html_url": "https://github.com/jupyter/notebook/issues/2285#issuecomment-320961079",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2285",
    "id": 320961079,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMDk2MTA3OQ==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-08-08T13:47:50Z",
    "updated_at": "2017-08-08T13:47:50Z",
    "author_association": "MEMBER",
    "body": "I think this might be fixed by ipython/traitlets#399. That's not yet released, but could you try installing traitlets from master and see if that fixes it?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/320967213",
    "html_url": "https://github.com/jupyter/notebook/issues/2285#issuecomment-320967213",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2285",
    "id": 320967213,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMyMDk2NzIxMw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-08-08T14:08:47Z",
    "updated_at": "2017-08-08T14:08:47Z",
    "author_association": "MEMBER",
    "body": "I had another go at reproducing it on my Windows 8 VM, using a character which is not only non-ascii, but also outside the Windows code page it uses (before I tried with Ã©, which is in CP1252). I still can't replicate the problem, although miniconda refused to install into my user directory.",
    "performed_via_github_app": null
  }
]
