[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/123925256",
    "html_url": "https://github.com/jupyter/notebook/issues/223#issuecomment-123925256",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/223",
    "id": 123925256,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyMzkyNTI1Ng==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-23T01:24:08Z",
    "updated_at": "2015-07-23T01:24:08Z",
    "author_association": "MEMBER",
    "body": "Hm. This may be a configuration or environment issue. I can list, create, and open unicode filenames without issue on IPython 3.x and 4.x on both Python 2 and 3. I am on OS X 10.10.4 with Pythons from conda.\n\n<img width=\"324\" alt=\"screen shot 2015-07-22 at 18 22 26\" src=\"https://cloud.githubusercontent.com/assets/151929/8841123/c3fe443e-309e-11e5-9838-ee57b2d9f896.PNG\">\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/123940733",
    "html_url": "https://github.com/jupyter/notebook/issues/223#issuecomment-123940733",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/223",
    "id": 123940733,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyMzk0MDczMw==",
    "user": {
      "login": "nkeim",
      "id": 2985325,
      "node_id": "MDQ6VXNlcjI5ODUzMjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2985325?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nkeim",
      "html_url": "https://github.com/nkeim",
      "followers_url": "https://api.github.com/users/nkeim/followers",
      "following_url": "https://api.github.com/users/nkeim/following{/other_user}",
      "gists_url": "https://api.github.com/users/nkeim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nkeim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nkeim/subscriptions",
      "organizations_url": "https://api.github.com/users/nkeim/orgs",
      "repos_url": "https://api.github.com/users/nkeim/repos",
      "events_url": "https://api.github.com/users/nkeim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nkeim/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-23T02:47:59Z",
    "updated_at": "2015-07-23T02:47:59Z",
    "author_association": "NONE",
    "body": "Thanks! The environment for the notebook server spawned by JupyterHub could easily be the problem. It appears that `LANG` is not set by JupyterHub. \n\nWithin the world of the notebook server, the Python 3 interpreter (Ubuntu 14.04.1 LTS `/usr/bin/python3`) just doesn't like Unicode in filenames. `open('µm.txt', 'w').write('hi')` raises a `UnicodeEncodeError`. But when I run the same interpreter in my login environment, there's no problem... until I take away its `LANG=en_US.UTF-8`. \n\nStrangely I cannot reproduce this with Python 3 from Anaconda on my Mac, even if I deliberately give it `LANG=en_US.ASCII`.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/124211858",
    "html_url": "https://github.com/jupyter/notebook/issues/223#issuecomment-124211858",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/223",
    "id": 124211858,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNDIxMTg1OA==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-23T19:00:18Z",
    "updated_at": "2015-07-23T19:00:18Z",
    "author_association": "MEMBER",
    "body": "I think that makes sense - it's using the locale encoding to convert filenames to bytes. I think it only comes up on Linux, because OS X and Windows define how filenames are encoded independent of the locale.\n\nJupyterhub should probably ensure that the single-user server is started with appropriate locale settings so that it treats the filesystem as UTF-8.\n\nThe notebook server should fail more gracefully when there's a unicode problem with a filename. I'll have a look at that.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/124214177",
    "html_url": "https://github.com/jupyter/notebook/issues/223#issuecomment-124214177",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/223",
    "id": 124214177,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNDIxNDE3Nw==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-23T19:09:53Z",
    "updated_at": "2015-07-23T19:12:38Z",
    "author_association": "MEMBER",
    "body": "@nkeim what version of JupyterHub? The Hub passes its LANG, LC env variables to the notebook children by default. Do you have any custom config?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/124217114",
    "html_url": "https://github.com/jupyter/notebook/issues/223#issuecomment-124217114",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/223",
    "id": 124217114,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNDIxNzExNA==",
    "user": {
      "login": "nkeim",
      "id": 2985325,
      "node_id": "MDQ6VXNlcjI5ODUzMjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2985325?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nkeim",
      "html_url": "https://github.com/nkeim",
      "followers_url": "https://api.github.com/users/nkeim/followers",
      "following_url": "https://api.github.com/users/nkeim/following{/other_user}",
      "gists_url": "https://api.github.com/users/nkeim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nkeim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nkeim/subscriptions",
      "organizations_url": "https://api.github.com/users/nkeim/orgs",
      "repos_url": "https://api.github.com/users/nkeim/repos",
      "events_url": "https://api.github.com/users/nkeim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nkeim/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-23T19:22:59Z",
    "updated_at": "2015-07-23T19:22:59Z",
    "author_association": "NONE",
    "body": "Deferring to @ellisonbg for the JupyterHub version — he maintains it here.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/124225340",
    "html_url": "https://github.com/jupyter/notebook/issues/223#issuecomment-124225340",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/223",
    "id": 124225340,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNDIyNTM0MA==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-23T20:05:08Z",
    "updated_at": "2015-07-23T20:05:08Z",
    "author_association": "MEMBER",
    "body": "@nkeim in that case, I know exactly what the problem is. The launch config (in supervisord) is not setting the LANG environment variable. This is in `/etc/supervisor/conf.d/jupyterhub.conf` The `environment` line should add:\n\n```\nenvironment=LANG=en_US.UTF-8,LC_ALL=en_US.UTF-8,...\n```\n\nto ensure that server processes get the right env.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/124226431",
    "html_url": "https://github.com/jupyter/notebook/issues/223#issuecomment-124226431",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/223",
    "id": 124226431,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNDIyNjQzMQ==",
    "user": {
      "login": "nkeim",
      "id": 2985325,
      "node_id": "MDQ6VXNlcjI5ODUzMjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2985325?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/nkeim",
      "html_url": "https://github.com/nkeim",
      "followers_url": "https://api.github.com/users/nkeim/followers",
      "following_url": "https://api.github.com/users/nkeim/following{/other_user}",
      "gists_url": "https://api.github.com/users/nkeim/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/nkeim/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/nkeim/subscriptions",
      "organizations_url": "https://api.github.com/users/nkeim/orgs",
      "repos_url": "https://api.github.com/users/nkeim/repos",
      "events_url": "https://api.github.com/users/nkeim/events{/privacy}",
      "received_events_url": "https://api.github.com/users/nkeim/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-23T20:10:40Z",
    "updated_at": "2015-07-23T20:10:40Z",
    "author_association": "NONE",
    "body": "@minrk Great, thanks!\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/124248801",
    "html_url": "https://github.com/jupyter/notebook/issues/223#issuecomment-124248801",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/223",
    "id": 124248801,
    "node_id": "MDEyOklzc3VlQ29tbWVudDEyNDI0ODgwMQ==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-07-23T21:50:02Z",
    "updated_at": "2015-07-23T21:50:02Z",
    "author_association": "MEMBER",
    "body": "#229 should stop it from breaking the rest of the list in such cases.\n",
    "performed_via_github_app": null
  }
]
