[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/827132582",
    "html_url": "https://github.com/jupyter/notebook/issues/6044#issuecomment-827132582",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/6044",
    "id": 827132582,
    "node_id": "MDEyOklzc3VlQ29tbWVudDgyNzEzMjU4Mg==",
    "user": {
      "login": "kevin-bates",
      "id": 22599560,
      "node_id": "MDQ6VXNlcjIyNTk5NTYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/22599560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevin-bates",
      "html_url": "https://github.com/kevin-bates",
      "followers_url": "https://api.github.com/users/kevin-bates/followers",
      "following_url": "https://api.github.com/users/kevin-bates/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevin-bates/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevin-bates/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevin-bates/subscriptions",
      "organizations_url": "https://api.github.com/users/kevin-bates/orgs",
      "repos_url": "https://api.github.com/users/kevin-bates/repos",
      "events_url": "https://api.github.com/users/kevin-bates/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevin-bates/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-04-26T20:40:19Z",
    "updated_at": "2021-04-26T20:40:19Z",
    "author_association": "MEMBER",
    "body": "Hi @ned2.  I'm unable to reproduce this issue using Notebook 6.3.0 and an svg file located within my notebook-dir hierarchy.  I've enabled debug and `python_logo.svg` is located in my `~/notebooks/images` directory with me running `jupyter notebook --debug --notebook-dir=~/notebooks`.  My markdown cell content is `<img src=\"images/python_logo.svg\">`.  I also get the following console output...\r\n```\r\n[D 13:25:46.522 NotebookApp] Redirecting /notebooks/images/python_logo.svg to /files/images/python_logo.svg\r\n[I 13:25:46.522 NotebookApp] 302 GET /notebooks/images/python_logo.svg (::1) 2.130000ms\r\n```\r\nIt looks like your jupyter modules are fairly recent.  What version of `notebook` are you running?  Could you please try enabling DEBUG logging and provide any related console output relative to the request?  Thanks.\r\n",
    "performed_via_github_app": null
  }
]
