[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/548602427",
    "html_url": "https://github.com/jupyter/notebook/issues/4994#issuecomment-548602427",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4994",
    "id": 548602427,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU0ODYwMjQyNw==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-10-31T23:01:59Z",
    "updated_at": "2019-10-31T23:01:59Z",
    "author_association": "MEMBER",
    "body": "What is the exact error you get ?\r\n\r\n`∂` is explicitly an uncommon unicode character that is meant to make sure we properly handle non western languages. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/550249332",
    "html_url": "https://github.com/jupyter/notebook/issues/4994#issuecomment-550249332",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4994",
    "id": 550249332,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU1MDI0OTMzMg==",
    "user": {
      "login": "qjtongkai",
      "id": 49664646,
      "node_id": "MDQ6VXNlcjQ5NjY0NjQ2",
      "avatar_url": "https://avatars.githubusercontent.com/u/49664646?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/qjtongkai",
      "html_url": "https://github.com/qjtongkai",
      "followers_url": "https://api.github.com/users/qjtongkai/followers",
      "following_url": "https://api.github.com/users/qjtongkai/following{/other_user}",
      "gists_url": "https://api.github.com/users/qjtongkai/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/qjtongkai/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/qjtongkai/subscriptions",
      "organizations_url": "https://api.github.com/users/qjtongkai/orgs",
      "repos_url": "https://api.github.com/users/qjtongkai/repos",
      "events_url": "https://api.github.com/users/qjtongkai/events{/privacy}",
      "received_events_url": "https://api.github.com/users/qjtongkai/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-11-06T10:32:47Z",
    "updated_at": "2019-11-06T10:32:47Z",
    "author_association": "NONE",
    "body": "Error occurs when I run test cases:\r\n`ImportError while loading conftest '/srv/src/notebook/notebook/tests/selenium/conftest.py'.\r\n/opt/tljh/user/lib/python3.6/ast.py:35: in parse\r\n    return compile(source, filename, mode, PyCF_ONLY_AST)\r\nE     File \"/srv/src/notebook/notebook/tests/selenium/conftest.py\", line 39\r\nE   SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0x88 in position 4: invalid start byte`\r\n\r\nIs this character for testing non western languages? My host is on language english.\r\n\r\n> What is the exact error you get ?\r\n> `∂` is explicitly an uncommon unicode character that is meant to make sure we properly handle non western languages.\r\n\r\n",
    "performed_via_github_app": null
  }
]
