[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/141638892",
    "html_url": "https://github.com/jupyter/notebook/issues/462#issuecomment-141638892",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/462",
    "id": 141638892,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MTYzODg5Mg==",
    "user": {
      "login": "lhk",
      "id": 1475537,
      "node_id": "MDQ6VXNlcjE0NzU1Mzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1475537?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lhk",
      "html_url": "https://github.com/lhk",
      "followers_url": "https://api.github.com/users/lhk/followers",
      "following_url": "https://api.github.com/users/lhk/following{/other_user}",
      "gists_url": "https://api.github.com/users/lhk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lhk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lhk/subscriptions",
      "organizations_url": "https://api.github.com/users/lhk/orgs",
      "repos_url": "https://api.github.com/users/lhk/repos",
      "events_url": "https://api.github.com/users/lhk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lhk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-19T09:06:37Z",
    "updated_at": "2015-09-19T09:06:37Z",
    "author_association": "NONE",
    "body": "I tried to install the outdated package, but there is a conflict with python 3.4\n    conda install -c https://conda.binstar.org/ska pygtk \n    Fetching package metadata: ......\n    Solving package specifications: ..\n    Error: Unsatisfiable package specifications.\n    Generating hint: \n    [      COMPLETE          ]|############################################################################## ############################################################################################################################| 100%\n\n```\nHint: the following packages conflict with each other:\n  - pygtk\n  - python 3.4*\n\nUse 'conda info pygtk' etc. to see the dependencies for each package.\n\nNote that the following features are enabled:\n  - gtk\n```\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/141835862",
    "html_url": "https://github.com/jupyter/notebook/issues/462#issuecomment-141835862",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/462",
    "id": 141835862,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MTgzNTg2Mg==",
    "user": {
      "login": "willingc",
      "id": 2680980,
      "node_id": "MDQ6VXNlcjI2ODA5ODA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2680980?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/willingc",
      "html_url": "https://github.com/willingc",
      "followers_url": "https://api.github.com/users/willingc/followers",
      "following_url": "https://api.github.com/users/willingc/following{/other_user}",
      "gists_url": "https://api.github.com/users/willingc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/willingc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/willingc/subscriptions",
      "organizations_url": "https://api.github.com/users/willingc/orgs",
      "repos_url": "https://api.github.com/users/willingc/repos",
      "events_url": "https://api.github.com/users/willingc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/willingc/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-20T21:27:59Z",
    "updated_at": "2015-09-20T21:27:59Z",
    "author_association": "MEMBER",
    "body": "@lhk From the first pastebin, it looks as if the last error message indicates that pygobject should be installed. `ImportError: Gtk3 backend requires pygobject to be installed.`\n\nSearching at anaconda.org, it looks as if there is a third party option conda option for installing pygobject at https://anaconda.org/fallen/pygobject. To install, `conda install -c https://conda.anaconda.org/fallen pygobject`.\n\nYou may wish to `conda remove` the pygtk package that you installed to avoid a conflict.\n\nI hope this helps. I'm on OS X so I can't test the linux easily for you. Good luck.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/142124951",
    "html_url": "https://github.com/jupyter/notebook/issues/462#issuecomment-142124951",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/462",
    "id": 142124951,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MjEyNDk1MQ==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-21T22:13:57Z",
    "updated_at": "2015-09-21T22:13:57Z",
    "author_association": "MEMBER",
    "body": "Well yes that seem to be (one of ) the correct way to install jupyter, which in itself works.\nThe issue is with the specific Gtk3 backend of matplotlib (which is not a jupyter issue). \n\nCan you re-try by starting your notebook with `%matplotlib inline` ? It might prevent matplotlib to try to import the gtk3 backend. \nlet see if that works. If it does we can also redirect you to the matplotlib and continuum developpers to see if they can help you to also have the gtk3 backend to works. \n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/142299310",
    "html_url": "https://github.com/jupyter/notebook/issues/462#issuecomment-142299310",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/462",
    "id": 142299310,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0MjI5OTMxMA==",
    "user": {
      "login": "lhk",
      "id": 1475537,
      "node_id": "MDQ6VXNlcjE0NzU1Mzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1475537?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lhk",
      "html_url": "https://github.com/lhk",
      "followers_url": "https://api.github.com/users/lhk/followers",
      "following_url": "https://api.github.com/users/lhk/following{/other_user}",
      "gists_url": "https://api.github.com/users/lhk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lhk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lhk/subscriptions",
      "organizations_url": "https://api.github.com/users/lhk/orgs",
      "repos_url": "https://api.github.com/users/lhk/repos",
      "events_url": "https://api.github.com/users/lhk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lhk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-09-22T14:07:45Z",
    "updated_at": "2015-09-22T14:07:45Z",
    "author_association": "NONE",
    "body": "Thank you very much\nFirst I tried inlining the output. That solves the problem\nThen I tried the pygobject package. Now I can import the library, but it doesn't seem to work.\n\nI tried this sample http://matplotlib.org/examples/shapes_and_collections/scatter_demo.html\n\nWith the inlining option, the scatterplot is drawn correctly.\nWith the pygobject package, a window opens to display the graph. But it stays empty.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/145926440",
    "html_url": "https://github.com/jupyter/notebook/issues/462#issuecomment-145926440",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/462",
    "id": 145926440,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NTkyNjQ0MA==",
    "user": {
      "login": "ellisonbg",
      "id": 27600,
      "node_id": "MDQ6VXNlcjI3NjAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/27600?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ellisonbg",
      "html_url": "https://github.com/ellisonbg",
      "followers_url": "https://api.github.com/users/ellisonbg/followers",
      "following_url": "https://api.github.com/users/ellisonbg/following{/other_user}",
      "gists_url": "https://api.github.com/users/ellisonbg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ellisonbg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ellisonbg/subscriptions",
      "organizations_url": "https://api.github.com/users/ellisonbg/orgs",
      "repos_url": "https://api.github.com/users/ellisonbg/repos",
      "events_url": "https://api.github.com/users/ellisonbg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ellisonbg/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-06T16:54:41Z",
    "updated_at": "2015-10-06T16:54:41Z",
    "author_association": "CONTRIBUTOR",
    "body": "Can you contact the matplotlib devs about this?\n",
    "performed_via_github_app": null
  }
]
