[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146516532",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146516532",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146516532,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjUxNjUzMg==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T11:58:43Z",
    "updated_at": "2015-10-08T11:58:43Z",
    "author_association": "MEMBER",
    "body": "Makes sense to test these things. @rgbkrk can you look at this one?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146543458",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146543458",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146543458,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjU0MzQ1OA==",
    "user": {
      "login": "rgbkrk",
      "id": 836375,
      "node_id": "MDQ6VXNlcjgzNjM3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/836375?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rgbkrk",
      "html_url": "https://github.com/rgbkrk",
      "followers_url": "https://api.github.com/users/rgbkrk/followers",
      "following_url": "https://api.github.com/users/rgbkrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/rgbkrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rgbkrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rgbkrk/subscriptions",
      "organizations_url": "https://api.github.com/users/rgbkrk/orgs",
      "repos_url": "https://api.github.com/users/rgbkrk/repos",
      "events_url": "https://api.github.com/users/rgbkrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rgbkrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T13:22:00Z",
    "updated_at": "2015-10-08T13:22:00Z",
    "author_association": "MEMBER",
    "body": "Seems fine. I've started using circleCI in other projects, it's pretty good. Do you have a link to your current builds? \n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146545422",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146545422",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146545422,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjU0NTQyMg==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T13:29:44Z",
    "updated_at": "2015-10-08T13:30:41Z",
    "author_association": "MEMBER",
    "body": "Sure, here is the most recent build ( https://circleci.com/gh/jakirkham/notebook/9 ).\n\nHere is the relevant error snippet. Looking at the test, what it does makes sense. This failure is on python2.\n\n```\nTest group: utils\n...............................................................................S........SSS...S.....S.S..S.E........S..S...............................\n======================================================================\nERROR: IPython.utils.tests.test_path.test_ensure_dir_exists\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/nose/case.py\", line 197, in runTest\n    self.test(*self.arg)\n  File \"/usr/local/lib/python2.7/dist-packages/IPython/utils/tests/test_path.py\", line 434, in test_ensure_dir_exists\n    path.ensure_dir_exists(d) # create it\n  File \"/usr/local/lib/python2.7/dist-packages/IPython/utils/path.py\", line 440, in ensure_dir_exists\n    if not os.path.exists(path):\n  File \"/usr/lib/python2.7/genericpath.py\", line 18, in exists\n    os.stat(path)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u2202' in position 25: ordinal not in range(128)\n```\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146571933",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146571933",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146571933,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjU3MTkzMw==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T15:00:19Z",
    "updated_at": "2015-10-08T15:00:19Z",
    "author_association": "MEMBER",
    "body": "There use to be more of these issues, but I added this line ( https://github.com/jupyter/notebook/blob/master/Dockerfile#L14 ), which sets `$PYTHONIOENCODING` to `UTF-8` and that removed all but this issue.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146632703",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146632703",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146632703,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjYzMjcwMw==",
    "user": {
      "login": "rgbkrk",
      "id": 836375,
      "node_id": "MDQ6VXNlcjgzNjM3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/836375?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rgbkrk",
      "html_url": "https://github.com/rgbkrk",
      "followers_url": "https://api.github.com/users/rgbkrk/followers",
      "following_url": "https://api.github.com/users/rgbkrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/rgbkrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rgbkrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rgbkrk/subscriptions",
      "organizations_url": "https://api.github.com/users/rgbkrk/orgs",
      "repos_url": "https://api.github.com/users/rgbkrk/repos",
      "events_url": "https://api.github.com/users/rgbkrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rgbkrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T17:35:42Z",
    "updated_at": "2015-10-08T17:35:42Z",
    "author_association": "MEMBER",
    "body": "I'm a fan of merging once it passes, otherwise this will sit in error for a long time. We should only be testing the notebook here and I'm not sure why Python2 is being tested here as well.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146638463",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146638463",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146638463,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjYzODQ2Mw==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T17:58:22Z",
    "updated_at": "2015-10-08T17:58:22Z",
    "author_association": "MEMBER",
    "body": "That sounds reasonable. If anybody is able to reproduce this failure outside of CircleCI, please let me know. At present, I can't seem to reproduce it.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146644194",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146644194",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146644194,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjY0NDE5NA==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T18:20:28Z",
    "updated_at": "2015-10-08T20:18:14Z",
    "author_association": "MEMBER",
    "body": "@rgbkrk, just so I follow, are you suggesting we drop Python 2 testing entirely?\n\nI'd be ok with keeping it, but maybe we could just skip this test, at present. It doesn't seem to affect building locally or on Docker Hub. It also completes successfully in a running container. Further, all the other python2 tests pass on Circle CI. We can always come back and see if we can get it to pass later.\n\nEdit: Turns out this issue showed up in python3 tests, as well. So, as the fix was relatively minor. It was worth making now.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146671996",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146671996",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146671996,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjY3MTk5Ng==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T20:09:37Z",
    "updated_at": "2015-10-08T20:16:06Z",
    "author_association": "MEMBER",
    "body": "Ha! I think I fixed it. ( https://circleci.com/gh/jakirkham/notebook/30 )\n\nWe will need to update iPython eventually though ( https://github.com/ipython/ipython/pull/8886 ).\n\nI have included a patch in this PR, which is applied in the container for the interim. If we need to keep the patch, it probably should be moved and renamed somehow.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146692872",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146692872",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146692872,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjY5Mjg3Mg==",
    "user": {
      "login": "rgbkrk",
      "id": 836375,
      "node_id": "MDQ6VXNlcjgzNjM3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/836375?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rgbkrk",
      "html_url": "https://github.com/rgbkrk",
      "followers_url": "https://api.github.com/users/rgbkrk/followers",
      "following_url": "https://api.github.com/users/rgbkrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/rgbkrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rgbkrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rgbkrk/subscriptions",
      "organizations_url": "https://api.github.com/users/rgbkrk/orgs",
      "repos_url": "https://api.github.com/users/rgbkrk/repos",
      "events_url": "https://api.github.com/users/rgbkrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rgbkrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T21:36:29Z",
    "updated_at": "2015-10-08T21:36:29Z",
    "author_association": "MEMBER",
    "body": "If you rebase and rekick your build, does it bring in the freshly merged patch instead?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146693323",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146693323",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146693323,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjY5MzMyMw==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T21:38:39Z",
    "updated_at": "2015-10-08T21:44:03Z",
    "author_association": "MEMBER",
    "body": "I will try and see what happens.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146696132",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146696132",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146696132,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjY5NjEzMg==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T21:52:24Z",
    "updated_at": "2015-10-08T22:04:57Z",
    "author_association": "MEMBER",
    "body": "It failed without the patch.\n\nSo, at present I believe it is `pip` installing `ipython`. I could try `pip` installing using `master` from `ipython` instead or perhaps even this commit ( https://github.com/ipython/ipython/commit/a58ab37122285adf8f79bd76ded718a777ae3a7c ).\n\nWhat would you like me to do?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146709932",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146709932",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146709932,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjcwOTkzMg==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T22:50:30Z",
    "updated_at": "2015-10-09T00:30:38Z",
    "author_association": "MEMBER",
    "body": "So, `pip` installing was working. However, I am having some issues installing packages on Circle CI now.\n\nFor those curious about size of layers, this did not make a noticeable difference.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146715661",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146715661",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146715661,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjcxNTY2MQ==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-08T23:32:37Z",
    "updated_at": "2015-10-09T00:07:59Z",
    "author_association": "MEMBER",
    "body": "I suspect something is broken with the docker image `ubuntu:14.04`. There was a push about an hour ago.\n\nTurns out I was not able to reproduce this issue as I did not have the most recent image of `ubuntu:14.04`. After pulling the most recent, I am able to reproduce it locally.\n\nAdded an issue here ( https://github.com/docker-library/official-images/issues/1110 ).\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146725084",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146725084",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146725084,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjcyNTA4NA==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T00:28:03Z",
    "updated_at": "2015-10-09T00:32:26Z",
    "author_association": "MEMBER",
    "body": "It turns out the there was a minimal (non-development) python installed. As a consequence, we were unable install the development dependencies that are required. I added a step that removes this development version of python first, which seems to resolve this issue.\n\nThis surprisingly results in a ~0.5MB layer, but it is not a big deal.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146729625",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146729625",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146729625,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjcyOTYyNQ==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T01:09:53Z",
    "updated_at": "2015-10-09T01:09:53Z",
    "author_association": "MEMBER",
    "body": "Build now passes ( https://circleci.com/gh/jakirkham/notebook/60 ).\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146846069",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146846069",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146846069,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0Njg0NjA2OQ==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T12:04:24Z",
    "updated_at": "2015-10-09T12:04:24Z",
    "author_association": "MEMBER",
    "body": "Based on feedback from @minrk, I have come up with an alternate fix for `ipython` in this PR ( https://github.com/ipython/ipython/pull/8887 ).\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146850187",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146850187",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146850187,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0Njg1MDE4Nw==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T12:27:11Z",
    "updated_at": "2015-10-09T12:27:11Z",
    "author_association": "MEMBER",
    "body": "Side note: I'm not sure whether you were aware of this, but repositories can be linked on Docker Hub (under Build Settings). This allows one to link it to the repository they are using as `FROM`. That way, when the upstream repository is pushed to or rebuilt it will trigger a rebuild of yours. This can be very handy in quickly diagnosing issues like the one I ran into last night. As the build errors, there will not be an image available to pull so you don't need to worry about somebody getting a broken image.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146908634",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146908634",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146908634,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjkwODYzNA==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T15:49:51Z",
    "updated_at": "2015-10-09T15:49:51Z",
    "author_association": "MEMBER",
    "body": "I'd like to try and explain what is going on with the encoding issues.\n\nOn a working build, we are able to easily change the locale with environment variables and see the following.\n\n```\nRUN python3 -c \"import sys; print(sys.getfilesystemencoding())\"\nutf-8\n```\n\nHowever, on Circle CI we are running into this bug ( https://bugs.launchpad.net/ubuntu/+source/langpack-locales/+bug/931717 ). As a result, we see this.\n\n```\nRUN python3 -c \"import sys; print(sys.getfilesystemencoding())\"\nascii\n```\n\nThere is a workaround proposed here ( https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/969299/comments/6 ). Though, I don't believe we can take advantage of this. When talking with someone from Circle CI, they stated that the best thing to do would be to have an image with the locale settings workaround done. I went ahead and did that and put it in the image here ( https://github.com/jakirkham/docker_ubuntu_14_04_locale_fix ). This fixes the problem and makes the patch unnecessary.\n\nWith these changes the build will pass. ( https://circleci.com/gh/jakirkham/notebook/75 )\n\nIf you wish to take this repo and license it as you see fit, I have no problem. I only have the two constraints. It needs to be open sourced (I don't care BSD or whatever) and I would like credit for the work I did. Once the logistics of how this should be setup are addressed, I will cobble these changes back together in this PR.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146916183",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146916183",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146916183,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjkxNjE4Mw==",
    "user": {
      "login": "rgbkrk",
      "id": 836375,
      "node_id": "MDQ6VXNlcjgzNjM3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/836375?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rgbkrk",
      "html_url": "https://github.com/rgbkrk",
      "followers_url": "https://api.github.com/users/rgbkrk/followers",
      "following_url": "https://api.github.com/users/rgbkrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/rgbkrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rgbkrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rgbkrk/subscriptions",
      "organizations_url": "https://api.github.com/users/rgbkrk/orgs",
      "repos_url": "https://api.github.com/users/rgbkrk/repos",
      "events_url": "https://api.github.com/users/rgbkrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rgbkrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T16:19:27Z",
    "updated_at": "2015-10-09T16:19:27Z",
    "author_association": "MEMBER",
    "body": "Sorry to totally siderail, but does any of this issue come up with Ubuntu 15.04?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146923871",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146923871",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146923871,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjkyMzg3MQ==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T16:35:59Z",
    "updated_at": "2015-10-09T17:56:27Z",
    "author_association": "MEMBER",
    "body": "I think I did a poor job of explaining. Sorry about that. Here's the TLDR:\n\nThe problem is an LXC AppArmor configuration issue on Circle CI, which blocks this encoding change.\n\nThe workaround is to do that step not on Circle CI (e.g. Docker Hub) and use it as our new base image.\n\nAlternatively, if you have another CI that you like with Docker support, we could try that.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146937752",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146937752",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146937752,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NjkzNzc1Mg==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T17:20:49Z",
    "updated_at": "2015-10-09T17:20:49Z",
    "author_association": "MEMBER",
    "body": "I should add building locally and on docker still result in working builds. This was built from my branch `docker_ci_3` ( https://hub.docker.com/r/jakirkham/notebook ).\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/146991682",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-146991682",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 146991682,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0Njk5MTY4Mg==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-09T21:38:38Z",
    "updated_at": "2015-10-09T21:38:38Z",
    "author_association": "MEMBER",
    "body": "Maybe it would be ok if I merged this ( https://github.com/jakirkham/docker_ubuntu_14_04_locale_fix ) into ( https://github.com/jupyter/docker-stacks ). Thoughts @parente?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/147149510",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-147149510",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 147149510,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE0NzE0OTUxMA==",
    "user": {
      "login": "parente",
      "id": 153745,
      "node_id": "MDQ6VXNlcjE1Mzc0NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/153745?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/parente",
      "html_url": "https://github.com/parente",
      "followers_url": "https://api.github.com/users/parente/followers",
      "following_url": "https://api.github.com/users/parente/following{/other_user}",
      "gists_url": "https://api.github.com/users/parente/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/parente/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/parente/subscriptions",
      "organizations_url": "https://api.github.com/users/parente/orgs",
      "repos_url": "https://api.github.com/users/parente/repos",
      "events_url": "https://api.github.com/users/parente/events{/privacy}",
      "received_events_url": "https://api.github.com/users/parente/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2015-10-11T03:04:15Z",
    "updated_at": "2015-10-11T03:04:15Z",
    "author_association": "MEMBER",
    "body": "@jakirkham Sure. Can you send it as a PR against docker-stacks?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/174852646",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-174852646",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 174852646,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3NDg1MjY0Ng==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-26T06:27:38Z",
    "updated_at": "2016-01-26T06:27:38Z",
    "author_association": "MEMBER",
    "body": "Sorry for the long delay. I have added this PR ( https://github.com/jupyter/docker-stacks/pull/108 ). So that we can have a base image to use for CI here.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/175322911",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-175322911",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 175322911,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3NTMyMjkxMQ==",
    "user": {
      "login": "rgbkrk",
      "id": 836375,
      "node_id": "MDQ6VXNlcjgzNjM3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/836375?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rgbkrk",
      "html_url": "https://github.com/rgbkrk",
      "followers_url": "https://api.github.com/users/rgbkrk/followers",
      "following_url": "https://api.github.com/users/rgbkrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/rgbkrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rgbkrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rgbkrk/subscriptions",
      "organizations_url": "https://api.github.com/users/rgbkrk/orgs",
      "repos_url": "https://api.github.com/users/rgbkrk/repos",
      "events_url": "https://api.github.com/users/rgbkrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rgbkrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-27T01:08:08Z",
    "updated_at": "2016-01-27T01:08:08Z",
    "author_association": "MEMBER",
    "body": "Ok cool. Now I see why we should just merge the other PR.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/175684513",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-175684513",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 175684513,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3NTY4NDUxMw==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-27T15:18:54Z",
    "updated_at": "2016-01-27T15:18:54Z",
    "author_association": "MEMBER",
    "body": "Yeah, I think we couldn't think of anywhere else to put it. Unfortunately, we really need the locale to be UTF8, but CircleCI wasn't having it. So, setting it in a base image did the trick and allowed this image to behave the same with the added bonus of CI.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/175789810",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-175789810",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 175789810,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3NTc4OTgxMA==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-27T18:49:44Z",
    "updated_at": "2016-01-27T18:49:44Z",
    "author_association": "MEMBER",
    "body": "Still needs the base image. Though, should we switch the base image to debian since this is already scheduled for 5.0? That way it can be the same as the other docker images. Maybe that should be another PR though as there is already a bit to keep track of here.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/176541753",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-176541753",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 176541753,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3NjU0MTc1Mw==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-29T02:47:34Z",
    "updated_at": "2016-01-29T03:07:04Z",
    "author_association": "MEMBER",
    "body": "Tests run for this branch ( https://circleci.com/gh/jakirkham/notebook/179 ) using the new base image in docker-stack.\n\nAppears to be failing on one test ( `IPython.lib.tests.test_lexers.TestLexers:testIPythonLexer` ). Can reproduce this locally. Is this just a `pygments` issue?\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/176624293",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-176624293",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 176624293,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3NjYyNDI5Mw==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-29T07:41:49Z",
    "updated_at": "2016-01-29T07:41:58Z",
    "author_association": "MEMBER",
    "body": "It's just because this isn't based on master. The IPython tests aren't run in this Dockerfile, but yes it's a probably inconsequential change in pygments causing an IPython lexer test to fail.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/176745963",
    "html_url": "https://github.com/jupyter/notebook/pull/547#issuecomment-176745963",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/547",
    "id": 176745963,
    "node_id": "MDEyOklzc3VlQ29tbWVudDE3Njc0NTk2Mw==",
    "user": {
      "login": "jakirkham",
      "id": 3019665,
      "node_id": "MDQ6VXNlcjMwMTk2NjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3019665?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakirkham",
      "html_url": "https://github.com/jakirkham",
      "followers_url": "https://api.github.com/users/jakirkham/followers",
      "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
      "organizations_url": "https://api.github.com/users/jakirkham/orgs",
      "repos_url": "https://api.github.com/users/jakirkham/repos",
      "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakirkham/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-01-29T13:08:00Z",
    "updated_at": "2016-01-29T13:08:00Z",
    "author_association": "MEMBER",
    "body": "Ah right, I forgot the tests got removed from the Dockerfile in master. Great. Thanks everyone.\n",
    "performed_via_github_app": null
  }
]
