[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/291877747",
    "html_url": "https://github.com/jupyter/notebook/issues/2370#issuecomment-291877747",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2370",
    "id": 291877747,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI5MTg3Nzc0Nw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-04-05T14:24:46Z",
    "updated_at": "2017-04-05T14:24:46Z",
    "author_association": "MEMBER",
    "body": "That file [is part of notebook 5.0.0](https://github.com/jupyter/notebook/blob/5.0.0/notebook/services/contents/largefilemanager.py), so that looks like something has gone wrong with the installation. Try uninstalling all copies of notebook you can find - especially if there may be more than one package manager involved, e.g. pip and conda. Then install it again.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/291972138",
    "html_url": "https://github.com/jupyter/notebook/issues/2370#issuecomment-291972138",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2370",
    "id": 291972138,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI5MTk3MjEzOA==",
    "user": {
      "login": "m1cl",
      "id": 12177563,
      "node_id": "MDQ6VXNlcjEyMTc3NTYz",
      "avatar_url": "https://avatars.githubusercontent.com/u/12177563?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/m1cl",
      "html_url": "https://github.com/m1cl",
      "followers_url": "https://api.github.com/users/m1cl/followers",
      "following_url": "https://api.github.com/users/m1cl/following{/other_user}",
      "gists_url": "https://api.github.com/users/m1cl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/m1cl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/m1cl/subscriptions",
      "organizations_url": "https://api.github.com/users/m1cl/orgs",
      "repos_url": "https://api.github.com/users/m1cl/repos",
      "events_url": "https://api.github.com/users/m1cl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/m1cl/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-04-05T19:34:03Z",
    "updated_at": "2017-04-05T19:34:03Z",
    "author_association": "NONE",
    "body": "It worked!",
    "performed_via_github_app": null
  }
]
