[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/225977214",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-225977214",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 225977214,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNTk3NzIxNA==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-14T18:42:28Z",
    "updated_at": "2016-06-14T18:42:28Z",
    "author_association": "MEMBER",
    "body": "Thanks, we had a 4.2 release that **might** have fixed that. \nWill check. \n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/225977532",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-225977532",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 225977532,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNTk3NzUzMg==",
    "user": {
      "login": "amueller",
      "id": 449558,
      "node_id": "MDQ6VXNlcjQ0OTU1OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/449558?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amueller",
      "html_url": "https://github.com/amueller",
      "followers_url": "https://api.github.com/users/amueller/followers",
      "following_url": "https://api.github.com/users/amueller/following{/other_user}",
      "gists_url": "https://api.github.com/users/amueller/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amueller/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amueller/subscriptions",
      "organizations_url": "https://api.github.com/users/amueller/orgs",
      "repos_url": "https://api.github.com/users/amueller/repos",
      "events_url": "https://api.github.com/users/amueller/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amueller/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-14T18:43:36Z",
    "updated_at": "2016-06-14T18:43:36Z",
    "author_association": "NONE",
    "body": "ahh.. sorry missed that. I'm slow. I'll try and see if it keeps happening.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/225982937",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-225982937",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 225982937,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNTk4MjkzNw==",
    "user": {
      "login": "Carreau",
      "id": 335567,
      "node_id": "MDQ6VXNlcjMzNTU2Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/335567?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Carreau",
      "html_url": "https://github.com/Carreau",
      "followers_url": "https://api.github.com/users/Carreau/followers",
      "following_url": "https://api.github.com/users/Carreau/following{/other_user}",
      "gists_url": "https://api.github.com/users/Carreau/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Carreau/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Carreau/subscriptions",
      "organizations_url": "https://api.github.com/users/Carreau/orgs",
      "repos_url": "https://api.github.com/users/Carreau/repos",
      "events_url": "https://api.github.com/users/Carreau/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Carreau/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-14T19:01:25Z",
    "updated_at": "2016-06-14T19:01:25Z",
    "author_association": "MEMBER",
    "body": "No problem, we know people can't keep up with everything. \nAnd Python packaging is the worst, you can't know if there are available updates. \n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/225983740",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-225983740",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 225983740,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIyNTk4Mzc0MA==",
    "user": {
      "login": "amueller",
      "id": 449558,
      "node_id": "MDQ6VXNlcjQ0OTU1OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/449558?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amueller",
      "html_url": "https://github.com/amueller",
      "followers_url": "https://api.github.com/users/amueller/followers",
      "following_url": "https://api.github.com/users/amueller/following{/other_user}",
      "gists_url": "https://api.github.com/users/amueller/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amueller/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amueller/subscriptions",
      "organizations_url": "https://api.github.com/users/amueller/orgs",
      "repos_url": "https://api.github.com/users/amueller/repos",
      "events_url": "https://api.github.com/users/amueller/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amueller/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-06-14T19:04:15Z",
    "updated_at": "2016-06-14T19:04:25Z",
    "author_association": "NONE",
    "body": "Thanks. I'll reopen if it persists / reappears.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/233746671",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-233746671",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 233746671,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMzc0NjY3MQ==",
    "user": {
      "login": "amueller",
      "id": 449558,
      "node_id": "MDQ6VXNlcjQ0OTU1OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/449558?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amueller",
      "html_url": "https://github.com/amueller",
      "followers_url": "https://api.github.com/users/amueller/followers",
      "following_url": "https://api.github.com/users/amueller/following{/other_user}",
      "gists_url": "https://api.github.com/users/amueller/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amueller/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amueller/subscriptions",
      "organizations_url": "https://api.github.com/users/amueller/orgs",
      "repos_url": "https://api.github.com/users/amueller/repos",
      "events_url": "https://api.github.com/users/amueller/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amueller/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-19T19:55:12Z",
    "updated_at": "2016-07-19T19:55:12Z",
    "author_association": "NONE",
    "body": "Ok, I think I'm still seeing this.\nI have an anaconda installation with\n\n```\njupyter                   1.0.0                    py35_3  \njupyter_client            4.3.0                    py35_0  \njupyter_console           5.0.0                    py35_0  \njupyter_core              4.1.0                    py35_0  \nnotebook                  4.2.1                    py35_0  \n```\n\nAre these all the relevant packages? Is there a meta-package or something that I can update?\n\n```\n[E 14:51:04.173 NotebookApp] 500 DELETE /api/sessions/6ac79d17-f007-4714-9ade-54b563c73b9b (127.0.0.1) 1.52ms referer=http://localhost:8888/notebooks/02-supervised-learning.ipynb\n[E 14:51:06.871 NotebookApp] Unhandled error in API request\n    Traceback (most recent call last):\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/notebook/base/handlers.py\", line 458, in wrapper\n        except web.HTTPError as e:\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/tornado/gen.py\", line 1008, in run\n        value = future.result()\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py\", line 232, in result\n        raise_exc_info(self._exc_info)\n      File \"<string>\", line 3, in raise_exc_info\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/tornado/gen.py\", line 282, in wrapper\n        yielded = next(result)\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/sessions/handlers.py\", line 111, in delete\n        changes['path'] = notebook['path']\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py\", line 218, in delete_session\n        the session database\"\"\"\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py\", line 105, in shutdown_kernel\n        return super(MappingKernelManager, self).shutdown_kernel(kernel_id, now=now)\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py\", line 33, in wrapped\n        r = method(*args, **kwargs)\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/manager.py\", line 302, in shutdown_kernel\n        self.request_shutdown(restart=restart)\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/manager.py\", line 252, in request_shutdown\n        self.session.send(self._control_socket, msg)\n      File \"/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/session.py\", line 684, in send\n        stream.send_multipart(to_send, copy=copy)\n    AttributeError: 'NoneType' object has no attribute 'send_multipart'\n```\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/233814274",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-233814274",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 233814274,
    "node_id": "MDEyOklzc3VlQ29tbWVudDIzMzgxNDI3NA==",
    "user": {
      "login": "amueller",
      "id": 449558,
      "node_id": "MDQ6VXNlcjQ0OTU1OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/449558?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amueller",
      "html_url": "https://github.com/amueller",
      "followers_url": "https://api.github.com/users/amueller/followers",
      "following_url": "https://api.github.com/users/amueller/following{/other_user}",
      "gists_url": "https://api.github.com/users/amueller/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amueller/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amueller/subscriptions",
      "organizations_url": "https://api.github.com/users/amueller/orgs",
      "repos_url": "https://api.github.com/users/amueller/repos",
      "events_url": "https://api.github.com/users/amueller/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amueller/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-07-20T01:28:51Z",
    "updated_at": "2016-07-20T01:28:51Z",
    "author_association": "NONE",
    "body": "If it's any help, this particularly seems to happen with relatively large notebooks like 02 and 03 from here: https://github.com/amueller/introduction_to_ml_with_python\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/260097604",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-260097604",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 260097604,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI2MDA5NzYwNA==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-12T03:00:31Z",
    "updated_at": "2016-11-12T03:00:31Z",
    "author_association": "MEMBER",
    "body": "@amueller sorry to bother you again, do you have time to try with jupyter_client 4.4.0? If it still happens with that, then I guess that `request_shutdown` should check the control socket it's trying to send to. Something must be closing it before it tries to send the shutdown request.\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/262468742",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-262468742",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 262468742,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI2MjQ2ODc0Mg==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-23T09:38:43Z",
    "updated_at": "2016-11-23T09:38:43Z",
    "author_association": "MEMBER",
    "body": "I looked through, and if `request_shutdown` is called twice, this will happen. I couldn't figure out how request_shutdown can be called more than once, though. That's probably something subtle in the handlers here. In any case, jupyter/jupyter_client#226 should make it safer to call shutdown twice. I'm okay calling this one not a bug in this repo for now.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/262551207",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-262551207",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 262551207,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI2MjU1MTIwNw==",
    "user": {
      "login": "amueller",
      "id": 449558,
      "node_id": "MDQ6VXNlcjQ0OTU1OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/449558?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/amueller",
      "html_url": "https://github.com/amueller",
      "followers_url": "https://api.github.com/users/amueller/followers",
      "following_url": "https://api.github.com/users/amueller/following{/other_user}",
      "gists_url": "https://api.github.com/users/amueller/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/amueller/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/amueller/subscriptions",
      "organizations_url": "https://api.github.com/users/amueller/orgs",
      "repos_url": "https://api.github.com/users/amueller/repos",
      "events_url": "https://api.github.com/users/amueller/events{/privacy}",
      "received_events_url": "https://api.github.com/users/amueller/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-11-23T15:45:02Z",
    "updated_at": "2016-11-23T15:45:02Z",
    "author_association": "NONE",
    "body": "I thought I had replied to this, sorry. I didn't observe this any more, but given that it was non-deterministic, I'm not sure how strong a claim that is. I'm totally fine with closing for now.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/264414420",
    "html_url": "https://github.com/jupyter/notebook/issues/1544#issuecomment-264414420",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/1544",
    "id": 264414420,
    "node_id": "MDEyOklzc3VlQ29tbWVudDI2NDQxNDQyMA==",
    "user": {
      "login": "minrk",
      "id": 151929,
      "node_id": "MDQ6VXNlcjE1MTkyOQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/151929?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/minrk",
      "html_url": "https://github.com/minrk",
      "followers_url": "https://api.github.com/users/minrk/followers",
      "following_url": "https://api.github.com/users/minrk/following{/other_user}",
      "gists_url": "https://api.github.com/users/minrk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/minrk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/minrk/subscriptions",
      "organizations_url": "https://api.github.com/users/minrk/orgs",
      "repos_url": "https://api.github.com/users/minrk/repos",
      "events_url": "https://api.github.com/users/minrk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/minrk/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2016-12-02T09:46:10Z",
    "updated_at": "2016-12-02T09:46:10Z",
    "author_association": "MEMBER",
    "body": "@amueller thanks, keep us posted if you see it again!",
    "performed_via_github_app": null
  }
]
