[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405010150",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-405010150",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 405010150,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTAxMDE1MA==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-14T09:02:28Z",
    "updated_at": "2018-07-14T09:02:28Z",
    "author_association": "MEMBER",
    "body": "It's expected, although we know it's not ideal. Tab completion works by sending a message to the kernel asking for a list of completions. If the kernel is busy doing something else at the time, it doesn't reply.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405031630",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-405031630",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 405031630,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTAzMTYzMA==",
    "user": {
      "login": "stas00",
      "id": 10676103,
      "node_id": "MDQ6VXNlcjEwNjc2MTAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/10676103?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stas00",
      "html_url": "https://github.com/stas00",
      "followers_url": "https://api.github.com/users/stas00/followers",
      "following_url": "https://api.github.com/users/stas00/following{/other_user}",
      "gists_url": "https://api.github.com/users/stas00/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stas00/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stas00/subscriptions",
      "organizations_url": "https://api.github.com/users/stas00/orgs",
      "repos_url": "https://api.github.com/users/stas00/repos",
      "events_url": "https://api.github.com/users/stas00/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stas00/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-14T15:46:39Z",
    "updated_at": "2018-07-14T15:46:39Z",
    "author_association": "NONE",
    "body": "Thank you for confirming the current state of things, Thomas. \r\n\r\nAre you also saying that the design can't be changed to support a working TAB completion regardless of the state of the kernel? e.g. having a dedicated thread listening to typing activity, while having another thread doing the executions?\r\n\r\nThank you.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405040317",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-405040317",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 405040317,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTA0MDMxNw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-14T18:09:12Z",
    "updated_at": "2018-07-14T18:09:31Z",
    "author_association": "MEMBER",
    "body": "Completing from a secondary thread causes problems for some libraries that aren't expecting it - the IPython terminal interface does this at the moment, and we've had several bug reports about it. There's no easy way to fix this without redesigning how Jupyter works (edit: as far as I know).",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405041254",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-405041254",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 405041254,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTA0MTI1NA==",
    "user": {
      "login": "stas00",
      "id": 10676103,
      "node_id": "MDQ6VXNlcjEwNjc2MTAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/10676103?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stas00",
      "html_url": "https://github.com/stas00",
      "followers_url": "https://api.github.com/users/stas00/followers",
      "following_url": "https://api.github.com/users/stas00/following{/other_user}",
      "gists_url": "https://api.github.com/users/stas00/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stas00/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stas00/subscriptions",
      "organizations_url": "https://api.github.com/users/stas00/orgs",
      "repos_url": "https://api.github.com/users/stas00/repos",
      "events_url": "https://api.github.com/users/stas00/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stas00/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-14T18:24:59Z",
    "updated_at": "2018-07-14T18:25:19Z",
    "author_association": "NONE",
    "body": "Thank you for explaining the reason for this limitation, Thomas.\r\n\r\nTalking about redesign, do you by chance know whether jupyterlab has this limitation resolved or is planning to?\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405042625",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-405042625",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 405042625,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTA0MjYyNQ==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-14T18:49:04Z",
    "updated_at": "2018-07-14T18:49:04Z",
    "author_association": "MEMBER",
    "body": "I don't think so; it's a limitation around the way kernels work, and Jupyterlab doesn't change that.\r\n\r\nYou can get round it to a degree by doing some completion in the frontend. The notebook already has some simple frontend completion based on words you've used before in the notebook (or cell? I forget). It's tricky to do more without embedding a lot of knowledge about the kernel language, though.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/405145294",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-405145294",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 405145294,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQwNTE0NTI5NA==",
    "user": {
      "login": "stas00",
      "id": 10676103,
      "node_id": "MDQ6VXNlcjEwNjc2MTAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/10676103?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stas00",
      "html_url": "https://github.com/stas00",
      "followers_url": "https://api.github.com/users/stas00/followers",
      "following_url": "https://api.github.com/users/stas00/following{/other_user}",
      "gists_url": "https://api.github.com/users/stas00/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stas00/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stas00/subscriptions",
      "organizations_url": "https://api.github.com/users/stas00/orgs",
      "repos_url": "https://api.github.com/users/stas00/repos",
      "events_url": "https://api.github.com/users/stas00/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stas00/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-07-16T04:10:20Z",
    "updated_at": "2018-07-16T04:10:20Z",
    "author_association": "NONE",
    "body": "In which can this be added to the feature-request list? \r\n\r\ni.e. avail partial TAB completion functionality based on local words when the kernel is busy\r\n\r\nThank you!",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/496695914",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-496695914",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 496695914,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ5NjY5NTkxNA==",
    "user": {
      "login": "soerendip",
      "id": 3391614,
      "node_id": "MDQ6VXNlcjMzOTE2MTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/3391614?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/soerendip",
      "html_url": "https://github.com/soerendip",
      "followers_url": "https://api.github.com/users/soerendip/followers",
      "following_url": "https://api.github.com/users/soerendip/following{/other_user}",
      "gists_url": "https://api.github.com/users/soerendip/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/soerendip/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/soerendip/subscriptions",
      "organizations_url": "https://api.github.com/users/soerendip/orgs",
      "repos_url": "https://api.github.com/users/soerendip/repos",
      "events_url": "https://api.github.com/users/soerendip/events{/privacy}",
      "received_events_url": "https://api.github.com/users/soerendip/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-05-28T21:25:25Z",
    "updated_at": "2019-05-28T21:25:25Z",
    "author_association": "NONE",
    "body": "Same",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/549113275",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-549113275",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 549113275,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU0OTExMzI3NQ==",
    "user": {
      "login": "MariaValentina12",
      "id": 57312413,
      "node_id": "MDQ6VXNlcjU3MzEyNDEz",
      "avatar_url": "https://avatars.githubusercontent.com/u/57312413?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MariaValentina12",
      "html_url": "https://github.com/MariaValentina12",
      "followers_url": "https://api.github.com/users/MariaValentina12/followers",
      "following_url": "https://api.github.com/users/MariaValentina12/following{/other_user}",
      "gists_url": "https://api.github.com/users/MariaValentina12/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MariaValentina12/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MariaValentina12/subscriptions",
      "organizations_url": "https://api.github.com/users/MariaValentina12/orgs",
      "repos_url": "https://api.github.com/users/MariaValentina12/repos",
      "events_url": "https://api.github.com/users/MariaValentina12/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MariaValentina12/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-11-03T07:51:07Z",
    "updated_at": "2019-11-03T07:51:07Z",
    "author_association": "NONE",
    "body": "Is there a work around?\r\n\r\nThanks",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561804338",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-561804338",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 561804338,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTgwNDMzOA==",
    "user": {
      "login": "HakanKiymaz",
      "id": 57303299,
      "node_id": "MDQ6VXNlcjU3MzAzMjk5",
      "avatar_url": "https://avatars.githubusercontent.com/u/57303299?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HakanKiymaz",
      "html_url": "https://github.com/HakanKiymaz",
      "followers_url": "https://api.github.com/users/HakanKiymaz/followers",
      "following_url": "https://api.github.com/users/HakanKiymaz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HakanKiymaz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HakanKiymaz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HakanKiymaz/subscriptions",
      "organizations_url": "https://api.github.com/users/HakanKiymaz/orgs",
      "repos_url": "https://api.github.com/users/HakanKiymaz/repos",
      "events_url": "https://api.github.com/users/HakanKiymaz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HakanKiymaz/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-04T19:33:27Z",
    "updated_at": "2019-12-04T19:33:27Z",
    "author_association": "NONE",
    "body": "Did you try Help-Keyboard Shortcuts, and editing automatically indent selection or auto indent? I had the same problem and just solved it.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/561929612",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-561929612",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 561929612,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU2MTkyOTYxMg==",
    "user": {
      "login": "stas00",
      "id": 10676103,
      "node_id": "MDQ6VXNlcjEwNjc2MTAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/10676103?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stas00",
      "html_url": "https://github.com/stas00",
      "followers_url": "https://api.github.com/users/stas00/followers",
      "following_url": "https://api.github.com/users/stas00/following{/other_user}",
      "gists_url": "https://api.github.com/users/stas00/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stas00/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stas00/subscriptions",
      "organizations_url": "https://api.github.com/users/stas00/orgs",
      "repos_url": "https://api.github.com/users/stas00/repos",
      "events_url": "https://api.github.com/users/stas00/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stas00/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-12-05T01:51:25Z",
    "updated_at": "2019-12-05T01:51:50Z",
    "author_association": "NONE",
    "body": "I am having a hard time understanding the relevance of your suggestion, @HakanKiymaz - what does it have to do with indent? Which problem did you solve?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/628977512",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-628977512",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 628977512,
    "node_id": "MDEyOklzc3VlQ29tbWVudDYyODk3NzUxMg==",
    "user": {
      "login": "Berkat0789",
      "id": 24399408,
      "node_id": "MDQ6VXNlcjI0Mzk5NDA4",
      "avatar_url": "https://avatars.githubusercontent.com/u/24399408?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Berkat0789",
      "html_url": "https://github.com/Berkat0789",
      "followers_url": "https://api.github.com/users/Berkat0789/followers",
      "following_url": "https://api.github.com/users/Berkat0789/following{/other_user}",
      "gists_url": "https://api.github.com/users/Berkat0789/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Berkat0789/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Berkat0789/subscriptions",
      "organizations_url": "https://api.github.com/users/Berkat0789/orgs",
      "repos_url": "https://api.github.com/users/Berkat0789/repos",
      "events_url": "https://api.github.com/users/Berkat0789/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Berkat0789/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-05-15T01:47:18Z",
    "updated_at": "2020-05-15T01:47:18Z",
    "author_association": "NONE",
    "body": "Best fix for this is using Anaconda or what ever IDE is to create a new environment. I know its a hassle to reinstall your libraries but the new environment will work with tabbing to autocomplete",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/628978814",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-628978814",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 628978814,
    "node_id": "MDEyOklzc3VlQ29tbWVudDYyODk3ODgxNA==",
    "user": {
      "login": "stas00",
      "id": 10676103,
      "node_id": "MDQ6VXNlcjEwNjc2MTAz",
      "avatar_url": "https://avatars.githubusercontent.com/u/10676103?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/stas00",
      "html_url": "https://github.com/stas00",
      "followers_url": "https://api.github.com/users/stas00/followers",
      "following_url": "https://api.github.com/users/stas00/following{/other_user}",
      "gists_url": "https://api.github.com/users/stas00/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/stas00/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/stas00/subscriptions",
      "organizations_url": "https://api.github.com/users/stas00/orgs",
      "repos_url": "https://api.github.com/users/stas00/repos",
      "events_url": "https://api.github.com/users/stas00/events{/privacy}",
      "received_events_url": "https://api.github.com/users/stas00/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-05-15T01:51:40Z",
    "updated_at": "2020-05-15T01:51:40Z",
    "author_association": "NONE",
    "body": "My hunch is that you're referring to a different issue. I'm not sure how a different environment can make any difference if there was no change in the core of the software. Unless there was one, then please kindly indicate the change that affects this issue. Thank you.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/714451193",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-714451193",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 714451193,
    "node_id": "MDEyOklzc3VlQ29tbWVudDcxNDQ1MTE5Mw==",
    "user": {
      "login": "johakaishi",
      "id": 53429825,
      "node_id": "MDQ6VXNlcjUzNDI5ODI1",
      "avatar_url": "https://avatars.githubusercontent.com/u/53429825?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/johakaishi",
      "html_url": "https://github.com/johakaishi",
      "followers_url": "https://api.github.com/users/johakaishi/followers",
      "following_url": "https://api.github.com/users/johakaishi/following{/other_user}",
      "gists_url": "https://api.github.com/users/johakaishi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/johakaishi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/johakaishi/subscriptions",
      "organizations_url": "https://api.github.com/users/johakaishi/orgs",
      "repos_url": "https://api.github.com/users/johakaishi/repos",
      "events_url": "https://api.github.com/users/johakaishi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/johakaishi/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-10-22T12:13:26Z",
    "updated_at": "2020-10-22T12:13:26Z",
    "author_association": "NONE",
    "body": "I have an issue where tab completion doesn't work full stop. I've checked that all cells above have been run, so it should tab complete.\r\n\r\nIn a cell:\r\n`import pandas as pd`\r\n\r\nSeparate cell:\r\n`pd.DataFrame`\r\n\r\nIn theory, you should be able to type pd.Da + [tab] but nothing. Anyone else had a similar issue?\r\nThis goes for all other methods and attributes as well. pd.DataFrame was just an example.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/745701270",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-745701270",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 745701270,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc0NTcwMTI3MA==",
    "user": {
      "login": "fontanads",
      "id": 12212663,
      "node_id": "MDQ6VXNlcjEyMjEyNjYz",
      "avatar_url": "https://avatars.githubusercontent.com/u/12212663?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fontanads",
      "html_url": "https://github.com/fontanads",
      "followers_url": "https://api.github.com/users/fontanads/followers",
      "following_url": "https://api.github.com/users/fontanads/following{/other_user}",
      "gists_url": "https://api.github.com/users/fontanads/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fontanads/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fontanads/subscriptions",
      "organizations_url": "https://api.github.com/users/fontanads/orgs",
      "repos_url": "https://api.github.com/users/fontanads/repos",
      "events_url": "https://api.github.com/users/fontanads/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fontanads/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-12-16T01:20:42Z",
    "updated_at": "2020-12-16T01:20:42Z",
    "author_association": "NONE",
    "body": "> I have an issue where tab completion doesn't work full stop. I've checked that all cells above have been run, so it should tab complete.\r\n> \r\n> In a cell:\r\n> `import pandas as pd`\r\n> \r\n> Separate cell:\r\n> `pd.DataFrame`\r\n> \r\n> In theory, you should be able to type pd.Da + [tab] but nothing. Anyone else had a similar issue?\r\n> This goes for all other methods and attributes as well. pd.DataFrame was just an example.\r\n\r\n[I found a solution here:](https://stackoverflow.com/questions/40536560/ipython-and-jupyter-autocomplete-not-working)\r\nQuoting Ramon Martinez:\r\n\"The issue can be solved by using the following magic which deactivates jedi\r\n%config Completer.use_jedi = False\"\r\nThis worked for me.\r\nAs pointed in one comment, it seems to be a very recent issue, but I don't know what's the scenario to reproduce it.\r\nI just updated Anaconda to 1.10.0 and I have faced this problem in both Jupyter and Jupyter Lab (6.1.5 and 2.2.6, respectively) on Windows 10 Home Version 10.0.19041 Compilation19041.\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/766838924",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-766838924",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 766838924,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc2NjgzODkyNA==",
    "user": {
      "login": "tcapelle",
      "id": 18441985,
      "node_id": "MDQ6VXNlcjE4NDQxOTg1",
      "avatar_url": "https://avatars.githubusercontent.com/u/18441985?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tcapelle",
      "html_url": "https://github.com/tcapelle",
      "followers_url": "https://api.github.com/users/tcapelle/followers",
      "following_url": "https://api.github.com/users/tcapelle/following{/other_user}",
      "gists_url": "https://api.github.com/users/tcapelle/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tcapelle/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tcapelle/subscriptions",
      "organizations_url": "https://api.github.com/users/tcapelle/orgs",
      "repos_url": "https://api.github.com/users/tcapelle/repos",
      "events_url": "https://api.github.com/users/tcapelle/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tcapelle/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-01-25T14:05:13Z",
    "updated_at": "2021-01-25T14:30:15Z",
    "author_association": "NONE",
    "body": "On a freshly installed conda env I get this error when I try to autocomplete my imports (pressing tab when doing `from pathlib import ...`)\r\n```\r\n(jupyter)~/Apps/fastexport > jupyter lab                                                                                                                                                                                                                                 tcapelle at APY (--)(export)\r\n[I 2021-01-25 15:03:17.500 ServerApp] jupyterlab | extension was successfully linked.\r\n[W 2021-01-25 15:03:17.502 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.\r\n[I 2021-01-25 15:03:17.602 ServerApp] nbclassic | extension was successfully linked.\r\n[I 2021-01-25 15:03:17.629 LabApp] JupyterLab extension loaded from /home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/jupyterlab\r\n[I 2021-01-25 15:03:17.629 LabApp] JupyterLab application directory is /home/tcapelle/miniconda3/envs/jupyter/share/jupyter/lab\r\n[I 2021-01-25 15:03:17.631 ServerApp] jupyterlab | extension was successfully loaded.\r\n[I 2021-01-25 15:03:17.633 ServerApp] nbclassic | extension was successfully loaded.\r\n[I 2021-01-25 15:03:17.633 ServerApp] Serving notebooks from local directory: /home/tcapelle/Apps/fastexport\r\n[I 2021-01-25 15:03:17.633 ServerApp] Jupyter Server 1.2.2 is running at:\r\n[I 2021-01-25 15:03:17.633 ServerApp] http://localhost:8888/lab\r\n[I 2021-01-25 15:03:17.633 ServerApp]  or http://127.0.0.1:8888/lab\r\n[I 2021-01-25 15:03:17.633 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).\r\n[W 2021-01-25 15:03:17.635 ServerApp] No web browser found: could not locate runnable browser.\r\n[I 2021-01-25 15:03:20.545 ServerApp] 302 GET / (127.0.0.1) 0.48ms\r\n[W 2021-01-25 15:03:25.350 LabApp] Could not determine jupyterlab build status without nodejs\r\n[I 2021-01-25 15:03:26.931 ServerApp] Kernel started: cc4f68d5-23ed-43d7-9cd6-48934e11ecb6\r\n[IPKernelApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?\r\n[IPKernelApp] ERROR | Exception in message handler:\r\nTraceback (most recent call last):\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 265, in dispatch_shell\r\n    yield gen.maybe_future(handler(stream, idents, msg))\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\r\n    value = future.result()\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\r\n    yielded = ctx_run(next, result)\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 580, in complete_request\r\n    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 356, in do_complete\r\n    return self._experimental_do_complete(code, cursor_pos)\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 381, in _experimental_do_complete\r\n    completions = list(_rectify_completions(code, raw_completions))\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 484, in rectify_completions\r\n    completions = list(completions)\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 1815, in completions\r\n    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 1858, in _completions\r\n    matched_text, matches, matches_origin, jedi_matches = self._complete(\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 2026, in _complete\r\n    completions = self._jedi_matches(\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 1369, in _jedi_matches\r\n    interpreter = jedi.Interpreter(\r\n  File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/jedi/api/__init__.py\", line 725, in __init__\r\n    super().__init__(code, environment=environment,\r\nTypeError: __init__() got an unexpected keyword argument 'column'\r\n\r\n```",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/767248860",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-767248860",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 767248860,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc2NzI0ODg2MA==",
    "user": {
      "login": "Siarhei-Y",
      "id": 64788880,
      "node_id": "MDQ6VXNlcjY0Nzg4ODgw",
      "avatar_url": "https://avatars.githubusercontent.com/u/64788880?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Siarhei-Y",
      "html_url": "https://github.com/Siarhei-Y",
      "followers_url": "https://api.github.com/users/Siarhei-Y/followers",
      "following_url": "https://api.github.com/users/Siarhei-Y/following{/other_user}",
      "gists_url": "https://api.github.com/users/Siarhei-Y/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Siarhei-Y/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Siarhei-Y/subscriptions",
      "organizations_url": "https://api.github.com/users/Siarhei-Y/orgs",
      "repos_url": "https://api.github.com/users/Siarhei-Y/repos",
      "events_url": "https://api.github.com/users/Siarhei-Y/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Siarhei-Y/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-01-26T02:38:01Z",
    "updated_at": "2021-01-26T02:38:01Z",
    "author_association": "NONE",
    "body": "> On a freshly installed conda env I get this error when I try to autocomplete my imports (pressing tab when doing `from pathlib import ...`)\r\n> \r\n> ```\r\n> (jupyter)~/Apps/fastexport > jupyter lab                                                                                                                                                                                                                                 tcapelle at APY (--)(export)\r\n> [I 2021-01-25 15:03:17.500 ServerApp] jupyterlab | extension was successfully linked.\r\n> [W 2021-01-25 15:03:17.502 NotebookApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.\r\n> [I 2021-01-25 15:03:17.602 ServerApp] nbclassic | extension was successfully linked.\r\n> [I 2021-01-25 15:03:17.629 LabApp] JupyterLab extension loaded from /home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/jupyterlab\r\n> [I 2021-01-25 15:03:17.629 LabApp] JupyterLab application directory is /home/tcapelle/miniconda3/envs/jupyter/share/jupyter/lab\r\n> [I 2021-01-25 15:03:17.631 ServerApp] jupyterlab | extension was successfully loaded.\r\n> [I 2021-01-25 15:03:17.633 ServerApp] nbclassic | extension was successfully loaded.\r\n> [I 2021-01-25 15:03:17.633 ServerApp] Serving notebooks from local directory: /home/tcapelle/Apps/fastexport\r\n> [I 2021-01-25 15:03:17.633 ServerApp] Jupyter Server 1.2.2 is running at:\r\n> [I 2021-01-25 15:03:17.633 ServerApp] http://localhost:8888/lab\r\n> [I 2021-01-25 15:03:17.633 ServerApp]  or http://127.0.0.1:8888/lab\r\n> [I 2021-01-25 15:03:17.633 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).\r\n> [W 2021-01-25 15:03:17.635 ServerApp] No web browser found: could not locate runnable browser.\r\n> [I 2021-01-25 15:03:20.545 ServerApp] 302 GET / (127.0.0.1) 0.48ms\r\n> [W 2021-01-25 15:03:25.350 LabApp] Could not determine jupyterlab build status without nodejs\r\n> [I 2021-01-25 15:03:26.931 ServerApp] Kernel started: cc4f68d5-23ed-43d7-9cd6-48934e11ecb6\r\n> [IPKernelApp] WARNING | Eventloop or matplotlib integration failed. Is matplotlib installed?\r\n> [IPKernelApp] ERROR | Exception in message handler:\r\n> Traceback (most recent call last):\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 265, in dispatch_shell\r\n>     yield gen.maybe_future(handler(stream, idents, msg))\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/tornado/gen.py\", line 762, in run\r\n>     value = future.result()\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/tornado/gen.py\", line 234, in wrapper\r\n>     yielded = ctx_run(next, result)\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 580, in complete_request\r\n>     matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 356, in do_complete\r\n>     return self._experimental_do_complete(code, cursor_pos)\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 381, in _experimental_do_complete\r\n>     completions = list(_rectify_completions(code, raw_completions))\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 484, in rectify_completions\r\n>     completions = list(completions)\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 1815, in completions\r\n>     for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 1858, in _completions\r\n>     matched_text, matches, matches_origin, jedi_matches = self._complete(\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 2026, in _complete\r\n>     completions = self._jedi_matches(\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/IPython/core/completer.py\", line 1369, in _jedi_matches\r\n>     interpreter = jedi.Interpreter(\r\n>   File \"/home/tcapelle/miniconda3/envs/jupyter/lib/python3.8/site-packages/jedi/api/__init__.py\", line 725, in __init__\r\n>     super().__init__(code, environment=environment,\r\n> TypeError: __init__() got an unexpected keyword argument 'column'\r\n> ```\r\n\r\nSame",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/767406862",
    "html_url": "https://github.com/jupyter/notebook/issues/3763#issuecomment-767406862",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3763",
    "id": 767406862,
    "node_id": "MDEyOklzc3VlQ29tbWVudDc2NzQwNjg2Mg==",
    "user": {
      "login": "tcapelle",
      "id": 18441985,
      "node_id": "MDQ6VXNlcjE4NDQxOTg1",
      "avatar_url": "https://avatars.githubusercontent.com/u/18441985?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/tcapelle",
      "html_url": "https://github.com/tcapelle",
      "followers_url": "https://api.github.com/users/tcapelle/followers",
      "following_url": "https://api.github.com/users/tcapelle/following{/other_user}",
      "gists_url": "https://api.github.com/users/tcapelle/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/tcapelle/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/tcapelle/subscriptions",
      "organizations_url": "https://api.github.com/users/tcapelle/orgs",
      "repos_url": "https://api.github.com/users/tcapelle/repos",
      "events_url": "https://api.github.com/users/tcapelle/events{/privacy}",
      "received_events_url": "https://api.github.com/users/tcapelle/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2021-01-26T09:10:14Z",
    "updated_at": "2021-01-26T09:10:14Z",
    "author_association": "NONE",
    "body": "i knda of solved the issue downgrading jedi to 0.17.2",
    "performed_via_github_app": null
  }
]
