[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378180836",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378180836",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378180836,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODE4MDgzNg==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-03T09:04:39Z",
    "updated_at": "2018-04-03T09:04:39Z",
    "author_association": "MEMBER",
    "body": "> I tried to put \"jupyter kernelspec list\" on CMD but all I got is...\r\n\r\nOn Windows, you probably need to start an 'Anaconda prompt' from the start menu. This is still CMD, but it sets some things up so that you can access Python commands.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378385462",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378385462",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378385462,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODM4NTQ2Mg==",
    "user": {
      "login": "Nemo900",
      "id": 38008847,
      "node_id": "MDQ6VXNlcjM4MDA4ODQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/38008847?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Nemo900",
      "html_url": "https://github.com/Nemo900",
      "followers_url": "https://api.github.com/users/Nemo900/followers",
      "following_url": "https://api.github.com/users/Nemo900/following{/other_user}",
      "gists_url": "https://api.github.com/users/Nemo900/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Nemo900/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Nemo900/subscriptions",
      "organizations_url": "https://api.github.com/users/Nemo900/orgs",
      "repos_url": "https://api.github.com/users/Nemo900/repos",
      "events_url": "https://api.github.com/users/Nemo900/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Nemo900/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-03T20:25:00Z",
    "updated_at": "2018-04-03T20:25:00Z",
    "author_association": "NONE",
    "body": "@takluyver  Thanks for the reply. I tried to it in anaconda prompt and this is what I got:\r\n![image](https://user-images.githubusercontent.com/38008847/38274025-2af0820a-3796-11e8-87ed-a4e2ad02a88e.png)\r\n\r\nHow do I continue from here?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378386377",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378386377",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378386377,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODM4NjM3Nw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-03T20:27:21Z",
    "updated_at": "2018-04-03T20:27:21Z",
    "author_association": "MEMBER",
    "body": "The easiest thing is probably just to delete that directory - it should fall back on running the kernel on the same version of Python that runs your notebook server.\r\n\r\nIf you've got time to investigate, I'd be interested to see what directory it's pointing to that is invalid. Look for a `kernel.json` in that folder.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378388645",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378388645",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378388645,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODM4ODY0NQ==",
    "user": {
      "login": "Nemo900",
      "id": 38008847,
      "node_id": "MDQ6VXNlcjM4MDA4ODQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/38008847?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Nemo900",
      "html_url": "https://github.com/Nemo900",
      "followers_url": "https://api.github.com/users/Nemo900/followers",
      "following_url": "https://api.github.com/users/Nemo900/following{/other_user}",
      "gists_url": "https://api.github.com/users/Nemo900/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Nemo900/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Nemo900/subscriptions",
      "organizations_url": "https://api.github.com/users/Nemo900/orgs",
      "repos_url": "https://api.github.com/users/Nemo900/repos",
      "events_url": "https://api.github.com/users/Nemo900/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Nemo900/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-03T20:32:47Z",
    "updated_at": "2018-04-03T20:32:47Z",
    "author_association": "NONE",
    "body": "I found the kernel.json file. Should I delete it?\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378391995",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378391995",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378391995,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODM5MTk5NQ==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-03T20:40:52Z",
    "updated_at": "2018-04-03T20:40:52Z",
    "author_association": "MEMBER",
    "body": "I think deleting it will probably fix the issue, but if you'd like to post the contents of that file first, it might provide some hint of what went wrong. That could be useful if other people report the same error.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378392569",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378392569",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378392569,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODM5MjU2OQ==",
    "user": {
      "login": "Nemo900",
      "id": 38008847,
      "node_id": "MDQ6VXNlcjM4MDA4ODQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/38008847?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Nemo900",
      "html_url": "https://github.com/Nemo900",
      "followers_url": "https://api.github.com/users/Nemo900/followers",
      "following_url": "https://api.github.com/users/Nemo900/following{/other_user}",
      "gists_url": "https://api.github.com/users/Nemo900/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Nemo900/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Nemo900/subscriptions",
      "organizations_url": "https://api.github.com/users/Nemo900/orgs",
      "repos_url": "https://api.github.com/users/Nemo900/repos",
      "events_url": "https://api.github.com/users/Nemo900/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Nemo900/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-03T20:42:39Z",
    "updated_at": "2018-04-03T20:42:39Z",
    "author_association": "NONE",
    "body": "![image](https://user-images.githubusercontent.com/38008847/38274854-ae5e2f3c-3798-11e8-8759-fb1aadc2ad4b.png)\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378394110",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378394110",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378394110,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODM5NDExMA==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-03T20:48:07Z",
    "updated_at": "2018-04-03T20:48:07Z",
    "author_association": "MEMBER",
    "body": "Thanks. There's nothing obviously wrong there. I wonder if this is the\nwrong track. What's the directory where you're trying to create/open a\nnotebook? It might be a python 2 Unicode issue.\n\nOn Tue, 3 Apr 2018, 10:42 p.m. Nemo900, <notifications@github.com> wrote:\n\n> [image: image]\n> <https://user-images.githubusercontent.com/38008847/38274854-ae5e2f3c-3798-11e8-8759-fb1aadc2ad4b.png>\n>\n> —\n> You are receiving this because you were mentioned.\n> Reply to this email directly, view it on GitHub\n> <https://github.com/jupyter/notebook/issues/3489#issuecomment-378392569>,\n> or mute the thread\n> <https://github.com/notifications/unsubscribe-auth/AAUA9ZPTApy63EMeQeZ_FU1-XCP0xSapks5tk97AgaJpZM4TDnjk>\n> .\n>\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378395683",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378395683",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378395683,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODM5NTY4Mw==",
    "user": {
      "login": "Nemo900",
      "id": 38008847,
      "node_id": "MDQ6VXNlcjM4MDA4ODQ3",
      "avatar_url": "https://avatars.githubusercontent.com/u/38008847?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Nemo900",
      "html_url": "https://github.com/Nemo900",
      "followers_url": "https://api.github.com/users/Nemo900/followers",
      "following_url": "https://api.github.com/users/Nemo900/following{/other_user}",
      "gists_url": "https://api.github.com/users/Nemo900/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Nemo900/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Nemo900/subscriptions",
      "organizations_url": "https://api.github.com/users/Nemo900/orgs",
      "repos_url": "https://api.github.com/users/Nemo900/repos",
      "events_url": "https://api.github.com/users/Nemo900/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Nemo900/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-03T20:53:34Z",
    "updated_at": "2018-04-03T20:53:34Z",
    "author_association": "NONE",
    "body": "The problem was indeed a unicode issue, I had Hebrew in my directory so it didn't read it. \r\n\r\nThank you so much for all your help!",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/378534905",
    "html_url": "https://github.com/jupyter/notebook/issues/3489#issuecomment-378534905",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3489",
    "id": 378534905,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3ODUzNDkwNQ==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-04-04T09:14:36Z",
    "updated_at": "2018-04-04T09:14:36Z",
    "author_association": "MEMBER",
    "body": "No problem. If possible, I'd recommend using Python 3 - it's generally better at things like this.",
    "performed_via_github_app": null
  }
]
