[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/591554979",
    "html_url": "https://github.com/jupyter/notebook/issues/5253#issuecomment-591554979",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5253",
    "id": 591554979,
    "node_id": "MDEyOklzc3VlQ29tbWVudDU5MTU1NDk3OQ==",
    "user": {
      "login": "kevin-bates",
      "id": 22599560,
      "node_id": "MDQ6VXNlcjIyNTk5NTYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/22599560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevin-bates",
      "html_url": "https://github.com/kevin-bates",
      "followers_url": "https://api.github.com/users/kevin-bates/followers",
      "following_url": "https://api.github.com/users/kevin-bates/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevin-bates/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevin-bates/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevin-bates/subscriptions",
      "organizations_url": "https://api.github.com/users/kevin-bates/orgs",
      "repos_url": "https://api.github.com/users/kevin-bates/repos",
      "events_url": "https://api.github.com/users/kevin-bates/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevin-bates/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-02-26T17:48:15Z",
    "updated_at": "2020-02-26T17:48:15Z",
    "author_association": "MEMBER",
    "body": "This appears to be a snafu with the pywin32 package. You might try looking at #4980.\r\n\r\nGiven your traceback, I would try upgrading notebook.  \r\n\r\n`pip install notebook --upgrade`\r\n\r\nor, for conda envs,\r\n\r\n`conda update -c conda-forge notebook`\r\n\r\nOnce completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.3`, respectively.  \r\n\r\nOnce jupyter_core is on 4.6.3, there's another option that can bypass the pywin32 issue by setting `JUPYTER_ALLOW_INSECURE_WRITES=true`, but that should be a last resort and only if security is not paramount.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/644769966",
    "html_url": "https://github.com/jupyter/notebook/issues/5253#issuecomment-644769966",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/5253",
    "id": 644769966,
    "node_id": "MDEyOklzc3VlQ29tbWVudDY0NDc2OTk2Ng==",
    "user": {
      "login": "kevin-bates",
      "id": 22599560,
      "node_id": "MDQ6VXNlcjIyNTk5NTYw",
      "avatar_url": "https://avatars.githubusercontent.com/u/22599560?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kevin-bates",
      "html_url": "https://github.com/kevin-bates",
      "followers_url": "https://api.github.com/users/kevin-bates/followers",
      "following_url": "https://api.github.com/users/kevin-bates/following{/other_user}",
      "gists_url": "https://api.github.com/users/kevin-bates/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kevin-bates/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kevin-bates/subscriptions",
      "organizations_url": "https://api.github.com/users/kevin-bates/orgs",
      "repos_url": "https://api.github.com/users/kevin-bates/repos",
      "events_url": "https://api.github.com/users/kevin-bates/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kevin-bates/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2020-06-16T13:35:40Z",
    "updated_at": "2020-06-16T13:35:40Z",
    "author_association": "MEMBER",
    "body": "Closing this issue.  We can re-open if this is still a problem and the recommendations were not sufficient.",
    "performed_via_github_app": null
  }
]
