[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/304880426",
    "html_url": "https://github.com/jupyter/notebook/issues/2525#issuecomment-304880426",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/2525",
    "id": 304880426,
    "node_id": "MDEyOklzc3VlQ29tbWVudDMwNDg4MDQyNg==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2017-05-30T13:37:07Z",
    "updated_at": "2017-05-30T13:37:07Z",
    "author_association": "MEMBER",
    "body": "I guess it might be trying to run the server on a Python installation that doesn't look in the `site-packages` directory where tornado is installed.",
    "performed_via_github_app": null
  }
]
