[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/372155398",
    "html_url": "https://github.com/jupyter/notebook/issues/3406#issuecomment-372155398",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3406",
    "id": 372155398,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3MjE1NTM5OA==",
    "user": {
      "login": "mondeja",
      "id": 23049315,
      "node_id": "MDQ6VXNlcjIzMDQ5MzE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/23049315?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mondeja",
      "html_url": "https://github.com/mondeja",
      "followers_url": "https://api.github.com/users/mondeja/followers",
      "following_url": "https://api.github.com/users/mondeja/following{/other_user}",
      "gists_url": "https://api.github.com/users/mondeja/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mondeja/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mondeja/subscriptions",
      "organizations_url": "https://api.github.com/users/mondeja/orgs",
      "repos_url": "https://api.github.com/users/mondeja/repos",
      "events_url": "https://api.github.com/users/mondeja/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mondeja/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-11T22:28:44Z",
    "updated_at": "2018-03-11T22:28:44Z",
    "author_association": "NONE",
    "body": "Can you provide a example? This behaviour ensure that can be used later from an IPython environment.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/372159052",
    "html_url": "https://github.com/jupyter/notebook/issues/3406#issuecomment-372159052",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3406",
    "id": 372159052,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3MjE1OTA1Mg==",
    "user": {
      "login": "Exception4U",
      "id": 5507925,
      "node_id": "MDQ6VXNlcjU1MDc5MjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5507925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Exception4U",
      "html_url": "https://github.com/Exception4U",
      "followers_url": "https://api.github.com/users/Exception4U/followers",
      "following_url": "https://api.github.com/users/Exception4U/following{/other_user}",
      "gists_url": "https://api.github.com/users/Exception4U/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Exception4U/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Exception4U/subscriptions",
      "organizations_url": "https://api.github.com/users/Exception4U/orgs",
      "repos_url": "https://api.github.com/users/Exception4U/repos",
      "events_url": "https://api.github.com/users/Exception4U/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Exception4U/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-11T23:21:05Z",
    "updated_at": "2018-03-11T23:27:52Z",
    "author_association": "NONE",
    "body": "If I give` %matplotlib inline` as flag in notebook \r\nand now export this as python file from menu bar then we get following python conversion\r\n\r\n```\r\n# coding: utf-8\r\n\r\n# In[1]:\r\n\r\n\r\nget_ipython().magic(u'matplotlib inline')\r\n```\r\nand when we run this python file we get this error\r\n\r\n```\r\nTraceback (most recent call last):\r\n  File \"Untitled.py\", line 7, in <module>\r\n    get_ipython().magic(u'matplotlib inline')\r\nNameError: name 'get_ipython' is not defined\r\n```\r\n\r\nSo I want to propose if there  is better way to handle these ipython flag conversion while converting ipynb to py file\r\n\r\n",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/372304270",
    "html_url": "https://github.com/jupyter/notebook/issues/3406#issuecomment-372304270",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3406",
    "id": 372304270,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3MjMwNDI3MA==",
    "user": {
      "login": "mondeja",
      "id": 23049315,
      "node_id": "MDQ6VXNlcjIzMDQ5MzE1",
      "avatar_url": "https://avatars.githubusercontent.com/u/23049315?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mondeja",
      "html_url": "https://github.com/mondeja",
      "followers_url": "https://api.github.com/users/mondeja/followers",
      "following_url": "https://api.github.com/users/mondeja/following{/other_user}",
      "gists_url": "https://api.github.com/users/mondeja/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mondeja/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mondeja/subscriptions",
      "organizations_url": "https://api.github.com/users/mondeja/orgs",
      "repos_url": "https://api.github.com/users/mondeja/repos",
      "events_url": "https://api.github.com/users/mondeja/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mondeja/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-12T13:11:41Z",
    "updated_at": "2018-03-12T13:11:41Z",
    "author_association": "NONE",
    "body": "Because `get_ipython` is a function that only exists in IPython environment. ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/372305262",
    "html_url": "https://github.com/jupyter/notebook/issues/3406#issuecomment-372305262",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3406",
    "id": 372305262,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM3MjMwNTI2Mg==",
    "user": {
      "login": "Exception4U",
      "id": 5507925,
      "node_id": "MDQ6VXNlcjU1MDc5MjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5507925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Exception4U",
      "html_url": "https://github.com/Exception4U",
      "followers_url": "https://api.github.com/users/Exception4U/followers",
      "following_url": "https://api.github.com/users/Exception4U/following{/other_user}",
      "gists_url": "https://api.github.com/users/Exception4U/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Exception4U/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Exception4U/subscriptions",
      "organizations_url": "https://api.github.com/users/Exception4U/orgs",
      "repos_url": "https://api.github.com/users/Exception4U/repos",
      "events_url": "https://api.github.com/users/Exception4U/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Exception4U/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-03-12T13:15:19Z",
    "updated_at": "2018-03-12T13:15:19Z",
    "author_association": "NONE",
    "body": "I totally agree so this should not come when we convert to the python file ... isn't this a bug in iynb to python conversion module?",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/393449686",
    "html_url": "https://github.com/jupyter/notebook/issues/3406#issuecomment-393449686",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3406",
    "id": 393449686,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5MzQ0OTY4Ng==",
    "user": {
      "login": "Exception4U",
      "id": 5507925,
      "node_id": "MDQ6VXNlcjU1MDc5MjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5507925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Exception4U",
      "html_url": "https://github.com/Exception4U",
      "followers_url": "https://api.github.com/users/Exception4U/followers",
      "following_url": "https://api.github.com/users/Exception4U/following{/other_user}",
      "gists_url": "https://api.github.com/users/Exception4U/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Exception4U/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Exception4U/subscriptions",
      "organizations_url": "https://api.github.com/users/Exception4U/orgs",
      "repos_url": "https://api.github.com/users/Exception4U/repos",
      "events_url": "https://api.github.com/users/Exception4U/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Exception4U/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-05-31T08:13:53Z",
    "updated_at": "2018-05-31T08:13:53Z",
    "author_association": "NONE",
    "body": "this issue is not solved yet ",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/393644273",
    "html_url": "https://github.com/jupyter/notebook/issues/3406#issuecomment-393644273",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3406",
    "id": 393644273,
    "node_id": "MDEyOklzc3VlQ29tbWVudDM5MzY0NDI3Mw==",
    "user": {
      "login": "takluyver",
      "id": 327925,
      "node_id": "MDQ6VXNlcjMyNzkyNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/327925?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/takluyver",
      "html_url": "https://github.com/takluyver",
      "followers_url": "https://api.github.com/users/takluyver/followers",
      "following_url": "https://api.github.com/users/takluyver/following{/other_user}",
      "gists_url": "https://api.github.com/users/takluyver/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/takluyver/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/takluyver/subscriptions",
      "organizations_url": "https://api.github.com/users/takluyver/orgs",
      "repos_url": "https://api.github.com/users/takluyver/repos",
      "events_url": "https://api.github.com/users/takluyver/events{/privacy}",
      "received_events_url": "https://api.github.com/users/takluyver/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-05-31T19:09:24Z",
    "updated_at": "2018-05-31T19:09:24Z",
    "author_association": "MEMBER",
    "body": "We convert the magic commands to make it valid Python *syntax*. We don't get rid of them entirely, because some of them may affect what the code does. So if you've used magic commands, you have to go through and decide what to do with them: whether you can get rid of them entirely, or whether you need to replace them with more general Python code.\r\n\r\nFor some magic functions, we might be able to guess what you want, but not all of them, and the ones where we do guess we wouldn't always get right. So as `import this` says:\r\n\r\n> In the face of ambiguity, refuse the temptation to guess.",
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/447673634",
    "html_url": "https://github.com/jupyter/notebook/issues/3406#issuecomment-447673634",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/3406",
    "id": 447673634,
    "node_id": "MDEyOklzc3VlQ29tbWVudDQ0NzY3MzYzNA==",
    "user": {
      "login": "pharshalp",
      "id": 15175620,
      "node_id": "MDQ6VXNlcjE1MTc1NjIw",
      "avatar_url": "https://avatars.githubusercontent.com/u/15175620?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pharshalp",
      "html_url": "https://github.com/pharshalp",
      "followers_url": "https://api.github.com/users/pharshalp/followers",
      "following_url": "https://api.github.com/users/pharshalp/following{/other_user}",
      "gists_url": "https://api.github.com/users/pharshalp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pharshalp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pharshalp/subscriptions",
      "organizations_url": "https://api.github.com/users/pharshalp/orgs",
      "repos_url": "https://api.github.com/users/pharshalp/repos",
      "events_url": "https://api.github.com/users/pharshalp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pharshalp/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2018-12-16T20:35:06Z",
    "updated_at": "2018-12-16T20:35:06Z",
    "author_association": "NONE",
    "body": "Here is a trick that I use as a workaround...\r\nI put all the magic commands inside try-except blocks\r\n```python\r\ntry:\r\n    get_ipython()\r\n    %matplotlib notebook\r\nexcept NameError:\r\n    pass\r\n```\r\nthat way your notebook when converted to a script would run just fine.",
    "performed_via_github_app": null
  }
]
