[
  {
    "url": "https://api.github.com/repos/jupyter/notebook/issues/comments/521239809",
    "html_url": "https://github.com/jupyter/notebook/issues/4821#issuecomment-521239809",
    "issue_url": "https://api.github.com/repos/jupyter/notebook/issues/4821",
    "id": 521239809,
    "node_id": "MDEyOklzc3VlQ29tbWVudDUyMTIzOTgwOQ==",
    "user": {
      "login": "dstex",
      "id": 6628522,
      "node_id": "MDQ6VXNlcjY2Mjg1MjI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6628522?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dstex",
      "html_url": "https://github.com/dstex",
      "followers_url": "https://api.github.com/users/dstex/followers",
      "following_url": "https://api.github.com/users/dstex/following{/other_user}",
      "gists_url": "https://api.github.com/users/dstex/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dstex/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dstex/subscriptions",
      "organizations_url": "https://api.github.com/users/dstex/orgs",
      "repos_url": "https://api.github.com/users/dstex/repos",
      "events_url": "https://api.github.com/users/dstex/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dstex/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2019-08-14T13:12:34Z",
    "updated_at": "2019-08-14T13:12:34Z",
    "author_association": "NONE",
    "body": "Came here to note that I'm experiencing exactly the same behavior.\r\n",
    "performed_via_github_app": null
  }
]
